Repository cosmos/ibc-go, pull requests merged in 2021-04, with the labels that each got.

#108 Modify all message constructors to take in a string for address
  CHANGELOG.md
  modules/apps/transfer/client/cli/tx.go
  modules/apps/transfer/handler_test.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/msgs.go
  modules/apps/transfer/types/msgs_test.go
  modules/apps/transfer/types/packet_test.go
  modules/core/02-client/client/cli/tx.go
  modules/core/02-client/keeper/client_test.go
  modules/core/02-client/types/msgs.go
  modules/core/02-client/types/msgs_test.go
  modules/core/03-connection/client/cli/tx.go
  modules/core/03-connection/types/msgs.go
  modules/core/03-connection/types/msgs_test.go
  modules/core/04-channel/client/cli/tx.go
  modules/core/04-channel/types/msgs.go
  modules/core/04-channel/types/msgs_test.go
  modules/core/keeper/msg_server_test.go
  testing/chain.go
  testing/coordinator.go
Labels: automerge

#107 Revert application state changes on failed acknowledgements
  CHANGELOG.md
  docs/custom.md
  docs/migrations/ibc-migration-043.md
  modules/apps/transfer/handler_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/module.go
  modules/core/03-connection/keeper/verify_test.go
  modules/core/04-channel/keeper/packet_test.go
  modules/core/04-channel/keeper/timeout_test.go
  modules/core/04-channel/types/acknowledgement.go
  modules/core/04-channel/types/acknowledgement_test.go
  modules/core/05-port/types/module.go
  modules/core/exported/channel.go
  modules/core/keeper/msg_server.go
  modules/core/keeper/msg_server_test.go
  modules/light-clients/07-tendermint/types/client_state_test.go
  testing/chain.go
  testing/mock/mock.go
Labels: 20-transfer, core

#110 update README
  README.md
Labels: automerge, docs

#125 Efficient Consensus State Iteration
  CHANGELOG.md
  modules/light-clients/07-tendermint/types/store.go
  modules/light-clients/07-tendermint/types/store_test.go
  modules/light-clients/07-tendermint/types/update.go
  modules/light-clients/07-tendermint/types/update_test.go
Labels: automerge
