Repository cosmos/ibc-go, pull requests merged in 2022-02, with the labels that each got.

#779 rename portid and port prefix for interchain accounts submodules
  modules/apps/27-interchain-accounts/types/keys.go
Labels: automerge, backport-to-v3.0.x

#816 test: adding ica test for multiple controllers, single host
  modules/apps/27-interchain-accounts/controller/ibc_module_test.go
Labels: automerge, backport-to-v3.0.x

#792 the ica_auth page was renamed to auth-modules
  docs/.vuepress/config.js
Labels: automerge, backport-to-v3.0.x

#814 refactor: RegisterInterchainAccount
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/account_test.go
  modules/apps/27-interchain-accounts/types/errors.go
Labels: automerge, backport-to-v3.0.x

#833 refactor: reformat KeyOwnerAccount
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/host/keeper/keeper.go
  modules/apps/27-interchain-accounts/types/keys.go
  modules/apps/27-interchain-accounts/types/keys_test.go
Labels: automerge, backport-to-v3.0.x

#824 chore: adding encoding and txTypes fields to metadata
  docs/ibc/proto-docs.md
  modules/apps/27-interchain-accounts/controller/ibc_module_test.go
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/types/metadata.go
  modules/apps/27-interchain-accounts/types/metadata.pb.go
  modules/apps/27-interchain-accounts/types/metadata_test.go
  proto/ibc/applications/interchain_accounts/v1/metadata.proto
Labels: automerge, backport-to-v3.0.x

#811 refactor: include transaction response in ics27 channel acknowledgement
  docs/app-modules/interchain-accounts/auth-modules.md
  modules/apps/27-interchain-accounts/host/ibc_module.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/relay.go
  modules/apps/27-interchain-accounts/host/keeper/relay_test.go
Labels: automerge, backport-to-v3.0.x

#812 ADR 003: ICS27 Ack format
  docs/architecture/README.md
  docs/architecture/adr-003-ics27-acknowledgement.md
Labels: automerge

#842 test: ensure ics27 optimistic packet sends are disallowed
  modules/apps/27-interchain-accounts/controller/keeper/relay.go
  modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
Labels: backport-to-v3.0.x

#841 docs: add security model to ics27 docs
  docs/app-modules/interchain-accounts/overview.md
Labels: automerge, backport-to-v3.0.x

#846 test: Register using same owner address on multiple connections
  modules/apps/27-interchain-accounts/controller/keeper/account_test.go
Labels: backport-to-v3.0.x

#848 Added ChannelId to MsgChannelOpenInitResponse
  CHANGELOG.md
  docs/ibc/proto-docs.md
  modules/core/04-channel/types/tx.pb.go
  modules/core/keeper/msg_server.go
  proto/ibc/core/channel/v1/tx.proto
Labels: automerge, backport-to-v3.0.x

#885 fix: ica host OnRecvPacket error acknowledgement
  modules/apps/27-interchain-accounts/host/ibc_module.go
Labels: backport-to-v3.0.x

#847 chore: add defensive check to ensure metadata does not change when reopening an active channel
  modules/apps/27-interchain-accounts/controller/keeper/handshake.go
  modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
  modules/apps/27-interchain-accounts/host/keeper/handshake.go
  modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
  modules/apps/27-interchain-accounts/types/metadata.go
  modules/apps/27-interchain-accounts/types/metadata_test.go
Labels: automerge, backport-to-v3.0.x

#884 bug: use custom ante handler to reject redundant transactions in simapp
  CHANGELOG.md
  testing/simapp/ante_handler.go
  testing/simapp/app.go
Labels: backport-to-v3.0.x

#892 refactor: allow the mock module to be used multiple times as base ibc application in middleware stack
  CHANGELOG.md
  testing/README.md
  testing/mock/ibc_app.go
  testing/mock/ibc_module.go
  testing/mock/mock.go
  testing/simapp/app.go
Labels: automerge, backport-to-v3.0.x

#904 chore: add ParsePacketFromEvents testing helper function
  CHANGELOG.md
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/transfer_test.go
  testing/events.go
Labels: automerge

#921 fix: correctly claim capability for mock module, handle genesis exports
  testing/mock/mock.go
Labels: automerge, backport-to-v3.0.x

#926 refactor: use mock module for ics29 closing handshakes
  modules/apps/29-fee/ibc_module_test.go
Labels: automerge

#941 fix: classify client states without consensus states as expired
  modules/core/02-client/keeper/grpc_query_test.go
  modules/light-clients/07-tendermint/types/client_state.go
  modules/light-clients/07-tendermint/types/client_state_test.go
Labels: automerge, backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x

#973 Revert "feat: adding Pack/Unpack acknowledgement helper fns (#895)"
  CHANGELOG.md
  modules/core/04-channel/types/codec.go
  modules/core/04-channel/types/codec_test.go
Labels: automerge, backport-to-v3.0.x

#948 upgrade ics23 to v0.7
  CHANGELOG.md
  go.mod
  go.sum
Labels: backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x

#1020 testing: make testing.T public
  testing/chain.go
  testing/coordinator.go
  testing/endpoint.go
Labels: automerge, backport-to-v3.0.x
