Repository cosmos/ibc-go, pull requests merged in 2022-09, with the labels that each got.

#2172 CVE-2022-1650 Exposure of Sensitive Information to an Unauthorized Actor
  docs/package-lock.json
Labels: automerge

#2185 chore: remove duplicate imports
  modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
Labels: automerge

#2194 chore: update docs package-lock.json
  docs/package-lock.json
Labels: automerge

#2201 chore: fix broken link to bank module spec
  docs/apps/transfer/params.md
Labels: automerge, backport-to-v3.0.x, backport-to-v2.1.x, backport-to-v2.2.x, backport-to-v2.3.x, backport-to-v3.1.x, backport-to-v4.0.x, backport-to-v2.4.x, backport-to-v3.2.x, backport-to-v5.0.x, backport-to-v5.1.x

#2160 feat: add params for ics27 simulation
  modules/apps/27-interchain-accounts/module.go
  modules/apps/27-interchain-accounts/simulation/params.go
  modules/apps/27-interchain-accounts/simulation/params_test.go
Labels: backport-to-v5.0.x, backport-to-v5.1.x

#2140 chore: adding assertion of channel capabilities migration
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/keeper/migrations.go
  modules/apps/27-interchain-accounts/controller/keeper/migrations_test.go
  modules/apps/27-interchain-accounts/module.go
Labels: backport-to-v5.1.x

#2179 Add cli for submit tx transaction
  modules/apps/27-interchain-accounts/controller/client/cli/tx.go
  modules/apps/27-interchain-accounts/types/packet.go
Labels: automerge, backport-to-v5.1.x

#2177 chore: adding `IsMiddlewareEnabled` to `ActiveChannel` genesis type
  CHANGELOG.md
  docs/ibc/proto-docs.md
  modules/apps/27-interchain-accounts/controller/keeper/genesis.go
  modules/apps/27-interchain-accounts/controller/keeper/genesis_test.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/genesis/types/genesis.pb.go
  proto/ibc/applications/interchain_accounts/genesis/v1/genesis.proto
Labels: automerge, backport-to-v5.1.x

#2193 feat: adding interchain account address query to controller submodule
  CHANGELOG.md
  docs/client/swagger-ui/swagger.yaml
  docs/ibc/proto-docs.md
  modules/apps/27-interchain-accounts/controller/client/cli/cli.go
  modules/apps/27-interchain-accounts/controller/client/cli/query.go
  modules/apps/27-interchain-accounts/controller/keeper/grpc_query.go
  modules/apps/27-interchain-accounts/controller/keeper/grpc_query_test.go
  modules/apps/27-interchain-accounts/controller/types/query.pb.go
  modules/apps/27-interchain-accounts/controller/types/query.pb.gw.go
  proto/ibc/applications/interchain_accounts/controller/v1/query.proto
Labels: automerge, backport-to-v5.1.x

#2190 chore: adding x/group to simapp
  CHANGELOG.md
  testing/simapp/app.go
Labels: automerge, backport-to-v5.1.x

#2248 Adding call to underlying app to OnChanCloseConfirm
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
Labels: backport-to-v6.0.x

#2255 chore: rename `SubmitTx` to `SendTx`
  docs/ibc/proto-docs.md
  modules/apps/27-interchain-accounts/controller/client/cli/cli.go
  modules/apps/27-interchain-accounts/controller/client/cli/tx.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
  modules/apps/27-interchain-accounts/controller/types/codec.go
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/controller/types/msgs_test.go
  modules/apps/27-interchain-accounts/controller/types/tx.pb.go
  proto/ibc/applications/interchain_accounts/controller/v1/tx.proto
Labels: backport-to-v6.0.x

#2215 chore: add IsMiddlewareEnabled key to simulation store decoder
  modules/apps/27-interchain-accounts/simulation/decoder.go
  modules/apps/27-interchain-accounts/simulation/decoder_test.go
Labels: automerge, backport-to-v6.0.x

#2258 Addressing small nits for channel capability migrations
  modules/apps/27-interchain-accounts/controller/migrations/v5/migrations.go
Labels: backport-to-v6.0.x

#2250 Removing getting of the capability in controller message server
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
Labels: backport-to-v6.0.x

#2252 add ica module to simulation manager
  testing/simapp/app.go
Labels: backport-to-v5.0.x, backport-to-v6.0.x

#2282 Fix error in Code Coverage workflow
  .github/workflows/test.yml
Labels: backport-to-v5.0.x, backport-to-v6.0.x

#2308 fix: add nil checks for controller and host keeper services
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/keeper/migrations.go
  modules/apps/27-interchain-accounts/module.go
Labels: automerge, backport-to-v3.0.x, backport-to-v3.1.x, backport-to-v4.0.x, backport-to-v3.2.x, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v3.3.x, backport-to-v4.1.x

#2260 Use connection id instead of channel id in IsMiddlewareEnabled
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/genesis.go
  modules/apps/27-interchain-accounts/controller/keeper/genesis_test.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/controller/keeper/migrations.go
  modules/apps/27-interchain-accounts/controller/keeper/migrations_test.go
  modules/apps/27-interchain-accounts/types/keys.go
Labels: backport-to-v6.0.x

#2220 Adding `paramsKeeper.Subspace(icahosttypes.SubModuleName)`
  docs/apps/interchain-accounts/integration.md
Labels: backport-to-v3.0.x, backport-to-v3.1.x, backport-to-v4.0.x, backport-to-v3.2.x, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v3.3.x, backport-to-v4.1.x

#2338 fix broken link/update link
  docs/ibc/relayer.md
Labels: backport-to-v3.0.x, backport-to-v2.1.x, backport-to-v2.2.x, backport-to-v2.3.x, backport-to-v3.1.x, backport-to-v4.0.x, backport-to-v2.4.x, backport-to-v3.2.x, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v3.3.x, backport-to-v4.1.x

#2290 change DefaultParams on the host to allow all messages ("*")
  CHANGELOG.md
  modules/apps/27-interchain-accounts/host/types/keys.go
  modules/apps/27-interchain-accounts/host/types/params.go
Labels: backport-to-v6.0.x

#2302 fix: ica handshake reopening channel - use `GetAppVersion` in favour of `channel.Version`
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/keeper/handshake.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/handshake.go
  modules/apps/27-interchain-accounts/host/keeper/keeper.go
  testing/simapp/app.go
Labels: backport-to-v5.0.x, backport-to-v6.0.x

#2301 Update CLI to recover expired client for SDK 46 updates to gov module
  docs/ibc/proposals.md
Labels: docs, backport-to-v5.0.x, backport-to-v6.0.x

#2283 Move SetMiddlewareEnabled call ordering
  modules/apps/27-interchain-accounts/controller/keeper/account.go
Labels: backport-to-v6.0.x

#2352 chore: revert changing error code
  modules/apps/27-interchain-accounts/controller/types/errors.go
Labels: backport-to-v6.0.x

#2257 Adding private sendTx function
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/keeper/relay.go
Labels: backport-to-v6.0.x

#2367 docs: update default value for `allow_messages` after #2290
  docs/apps/interchain-accounts/parameters.md
Labels: backport-to-v6.0.x

#2351 docs: include ics4Wrapper in `hostkeeper.NewKeeper` ics27 integration docs
  docs/apps/interchain-accounts/integration.md
Labels: backport-to-v5.0.x, backport-to-v6.0.x

#2355 chore: renaming ica migrations handler pkg version
  modules/apps/27-interchain-accounts/controller/migrations/v6/migrations.go
  modules/apps/27-interchain-accounts/controller/migrations/v6/migrations_test.go
Labels: automerge, backport-to-v6.0.x

#1826 docs: migration docs v4 to v5
  docs/apps/interchain-accounts/auth-modules.md
  docs/architecture/adr-003-ics27-acknowledgement.md
  docs/migrations/v2-to-v3.md
  docs/migrations/v4-to-v5.md
  testing/mock/ack.go
Labels: backport-to-v5.0.x, backport-to-v6.0.x

#2127 docs: updating v3->v4 migration docs with fee middleware
  docs/migrations/v3-to-v4.md
Labels: automerge, backport-to-v4.0.x, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v4.1.x

#2382 nit: update short description of ICA CLI commands
  modules/apps/27-interchain-accounts/client/cli/cli.go
  modules/apps/27-interchain-accounts/controller/client/cli/cli.go
  modules/apps/27-interchain-accounts/host/client/cli/cli.go
Labels: backport-to-v6.0.x

#2394 docs: add ics29 integration for sdk module
  docs/middleware/ics29-fee/integration.md
Labels: automerge, backport-to-v4.0.x, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v4.1.x

#2395 chore: remove unnecessary code
  CHANGELOG.md
  modules/apps/29-fee/keeper/keeper.go
  testing/simapp/app.go
Labels: automerge

#2297 Add host cli to generate ica packet data
  CHANGELOG.md
  modules/apps/27-interchain-accounts/client/cli/cli.go
  modules/apps/27-interchain-accounts/host/client/cli/cli.go
  modules/apps/27-interchain-accounts/host/client/cli/tx.go
  modules/apps/27-interchain-accounts/host/client/cli/tx_test.go
Labels: backport-to-v6.0.x

#2392 chore: updating 09-localhost migration code to v7
  modules/core/migrations/v7/migrations.go
  modules/core/migrations/v7/migrations_test.go
Labels: automerge

#2218 ADR 009: ICS 27 simplication
  docs/architecture/adr-009-v6-ics27-msgserver.md
Labels: automerge, backport-to-v6.0.x

#2280 Modify MsgSendTx fields based on audit
  docs/ibc/proto-docs.md
  modules/apps/27-interchain-accounts/controller/client/cli/tx.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/controller/types/msgs_test.go
  modules/apps/27-interchain-accounts/controller/types/tx.pb.go
  proto/ibc/applications/interchain_accounts/controller/v1/tx.proto
Labels: backport-to-v6.0.x

#2426 chore: add v4 to v5 migration docs to site
  docs/.vuepress/config.js
Labels: automerge, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v5.1.x

#2425 chore: add private send transfer function
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/relay.go
Labels: backport-to-v2.5.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2399 updated error calls with module names
  CHANGELOG.md
  modules/core/keeper/msg_server.go
Labels: automerge, backport-to-v6.0.x

#2383 chore: add v6 upgrade handler to simapp
  testing/simapp/app.go
  testing/simapp/upgrades/v6/upgrades.go
Labels: backport-to-v6.0.x

#2304 Adding GetChannelsWithPortPrefix function to 04-channel
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/keeper/migrations.go
  modules/apps/27-interchain-accounts/controller/keeper/migrations_test.go
  modules/apps/27-interchain-accounts/types/expected_keepers.go
  modules/core/04-channel/keeper/keeper.go
  modules/core/04-channel/keeper/keeper_test.go
  modules/core/04-channel/types/keys.go
Labels: backport-to-v6.0.x

#2423 chore: update migration template
  docs/migrations/migration-template.md
  docs/migrations/v4-to-v5.md
Labels: automerge

#2403 added switch case to detect blank pointers in keeper
  CHANGELOG.md
  modules/core/keeper/keeper.go
  modules/core/keeper/keeper_test.go
Labels: backport-to-v6.0.x
