Repository cosmos/ibc-go, pull requests merged in 2022-04, with the labels that each got.

#1160 imp: improve Logger performance
  CHANGELOG.md
  modules/core/04-channel/keeper/packet.go
  modules/core/04-channel/keeper/timeout.go
Labels: automerge, improvement, backport-to-v3.0.x

#276 ICS 29: Fee Middleware
  docs/architecture/README.md
  docs/architecture/adr-004-ics29-lock-fee-module.md
  docs/ibc/proto-docs.md
  modules/apps/29-fee/client/cli/cli.go
  modules/apps/29-fee/client/cli/query.go
  modules/apps/29-fee/client/cli/tx.go
  modules/apps/29-fee/fee_test.go
  modules/apps/29-fee/ibc_module.go
  modules/apps/29-fee/ibc_module_test.go
  modules/apps/29-fee/keeper/escrow.go
  modules/apps/29-fee/keeper/escrow_test.go
  modules/apps/29-fee/keeper/events.go
  modules/apps/29-fee/keeper/genesis.go
  modules/apps/29-fee/keeper/genesis_test.go
  modules/apps/29-fee/keeper/grpc_query.go
  modules/apps/29-fee/keeper/grpc_query_test.go
  modules/apps/29-fee/keeper/keeper.go
  modules/apps/29-fee/keeper/keeper_test.go
  modules/apps/29-fee/keeper/msg_server.go
  modules/apps/29-fee/keeper/msg_server_test.go
  modules/apps/29-fee/keeper/relay.go
  modules/apps/29-fee/keeper/relay_test.go
  modules/apps/29-fee/module.go
  modules/apps/29-fee/transfer_test.go
  modules/apps/29-fee/types/ack.go
  modules/apps/29-fee/types/ack.pb.go
  modules/apps/29-fee/types/codec.go
  modules/apps/29-fee/types/errors.go
  modules/apps/29-fee/types/events.go
  modules/apps/29-fee/types/expected_keepers.go
  modules/apps/29-fee/types/fee.go
  modules/apps/29-fee/types/fee.pb.go
  modules/apps/29-fee/types/fee_test.go
  modules/apps/29-fee/types/genesis.go
  modules/apps/29-fee/types/genesis.pb.go
  modules/apps/29-fee/types/genesis_test.go
  modules/apps/29-fee/types/keys.go
  modules/apps/29-fee/types/keys_test.go
  modules/apps/29-fee/types/metadata.pb.go
  modules/apps/29-fee/types/msgs.go
  modules/apps/29-fee/types/msgs_test.go
  modules/apps/29-fee/types/query.pb.go
  modules/apps/29-fee/types/query.pb.gw.go
  modules/apps/29-fee/types/tx.pb.go
  modules/apps/transfer/ibc_module_test.go
  modules/core/04-channel/types/channel.pb.go
  modules/core/04-channel/types/packet.go
  modules/core/04-channel/types/version.go
  proto/ibc/applications/fee/v1/ack.proto
  proto/ibc/applications/fee/v1/fee.proto
  proto/ibc/applications/fee/v1/genesis.proto
  proto/ibc/applications/fee/v1/metadata.proto
  proto/ibc/applications/fee/v1/query.proto
  proto/ibc/applications/fee/v1/tx.proto
  proto/ibc/core/channel/v1/channel.proto
  scripts/protocgen.sh
  testing/simapp/app.go
  testing/values.go
Labels: 29-fee

#1226 chore: fix go ctx arg naming in ics29 grpc queries
  modules/apps/29-fee/keeper/grpc_query.go
Labels: automerge

#1227 chore: ics29 module housekeeping cleanup
  modules/apps/29-fee/module.go
Labels: automerge

#1230 feat: adding CLI for getting incentivized packets on a specific channel
  CHANGELOG.md
  modules/apps/29-fee/client/cli/cli.go
  modules/apps/29-fee/client/cli/query.go
Labels: automerge

#1232 refactor: moving fn definition to bottom of file and switching params
  CHANGELOG.md
  modules/apps/29-fee/client/cli/query.go
  modules/apps/29-fee/client/cli/tx.go
  modules/apps/29-fee/ibc_module.go
  modules/apps/29-fee/ibc_module_test.go
  modules/apps/29-fee/keeper/escrow_test.go
  modules/apps/29-fee/keeper/genesis_test.go
  modules/apps/29-fee/keeper/grpc_query_test.go
  modules/apps/29-fee/keeper/keeper_test.go
  modules/apps/29-fee/keeper/msg_server.go
  modules/apps/29-fee/keeper/msg_server_test.go
  modules/apps/29-fee/keeper/relay.go
  modules/apps/29-fee/keeper/relay_test.go
  modules/apps/29-fee/types/genesis_test.go
  modules/apps/29-fee/types/keys.go
  modules/apps/29-fee/types/keys_test.go
  modules/apps/29-fee/types/msgs_test.go
  modules/core/04-channel/types/packet.go
Labels: automerge

#1244 refactor: Fix RefundFeesOnChannel
  modules/apps/29-fee/ibc_module.go
  modules/apps/29-fee/ibc_module_test.go
  modules/apps/29-fee/keeper/escrow.go
  modules/apps/29-fee/keeper/escrow_test.go
  modules/apps/29-fee/keeper/keeper.go
  modules/apps/29-fee/keeper/keeper_test.go
  modules/apps/29-fee/transfer_test.go
Labels: automerge

#1255 docs: replace links in apps with correct ones
  docs/ibc/apps.md
Labels: automerge, backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x, backport-to-v1.4.x, backport-to-v2.2.x

#1256 update godoc of `RegisterInterchainAccount`
  modules/apps/27-interchain-accounts/controller/keeper/account.go
Labels: automerge, backport-to-v3.0.x

#1253 isolate packet fee distribution for on acknowledgement and on timeout into separate functions
  modules/apps/29-fee/keeper/escrow.go
Labels: automerge

#1263 Update supported release lines
  RELEASES.md
Labels: automerge

#1251 ics29: gracefully handle escrow out of balance edge case during fee distribution
  modules/apps/29-fee/ibc_module.go
  modules/apps/29-fee/keeper/escrow.go
  modules/apps/29-fee/keeper/escrow_test.go
  modules/apps/29-fee/keeper/genesis_test.go
  modules/apps/29-fee/keeper/grpc_query_test.go
  modules/apps/29-fee/keeper/keeper_test.go
  modules/apps/29-fee/keeper/msg_server_test.go
Labels: automerge

#1272 add missing changelog entry for bump of sdk 0.45.3
  CHANGELOG.md
Labels: automerge, backport-to-v3.0.x, backport-to-v1.4.x, backport-to-v2.2.x

#1022 feat: Add GetAppVersion to ICS4Wrapper
  CHANGELOG.md
  docs/ibc/middleware/develop.md
  modules/apps/27-interchain-accounts/controller/ibc_module.go
  modules/apps/27-interchain-accounts/controller/ibc_module_test.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/types/expected_keepers.go
  modules/apps/29-fee/ibc_module.go
  modules/apps/29-fee/ibc_module_test.go
  modules/apps/29-fee/keeper/relay.go
  modules/apps/29-fee/keeper/relay_test.go
  modules/apps/29-fee/types/expected_keepers.go
  modules/core/04-channel/keeper/keeper.go
  modules/core/04-channel/keeper/keeper_test.go
  modules/core/05-port/types/module.go
  testing/endpoint.go
Labels: automerge

#1301 chore: fix dead links from sdk default branch change
  docs/apps/interchain-accounts/transactions.md
Labels: backport-to-v3.0.x

#1281 update godoc for VerifyClientMessage
  modules/core/exported/client.go
Labels: automerge
