Repository cosmos/ibc-go, pull requests merged in 2022-11, with the labels that each got.

#2561 docs: ics27 v6 documentation updates
  docs/.vuepress/config.js
  docs/apps/interchain-accounts/active-channels.md
  docs/apps/interchain-accounts/auth-modules.md
  docs/apps/interchain-accounts/integration.md
  docs/apps/interchain-accounts/messages.md
  docs/apps/interchain-accounts/overview.md
  docs/apps/interchain-accounts/parameters.md
  docs/apps/interchain-accounts/transactions.md
  docs/package-lock.json
Labels: backport-to-v6.0.x

#2638 Add scopedkeeper as an interface to exported package
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/host/keeper/keeper.go
  modules/apps/27-interchain-accounts/types/expected_keepers.go
  modules/apps/transfer/keeper/keeper.go
  modules/apps/transfer/types/expected_keepers.go
  modules/core/04-channel/keeper/keeper.go
  modules/core/04-channel/types/expected_keepers.go
  modules/core/05-port/keeper/keeper.go
  modules/core/exported/expected_keepers.go
Labels: automerge, backport-to-v6.0.x

#2594 chore: add potential use cases documentation for ica
  docs/.vuepress/config.js
  docs/apps/interchain-accounts/active-channels.md
  docs/apps/interchain-accounts/auth-modules.md
  docs/apps/interchain-accounts/development.md
Labels: automerge, backport-to-v6.0.x

#2657 Testing: fix block proposer and allow Default gas to be modified
  CHANGELOG.md
  testing/chain.go
  testing/simapp/helpers/test_helpers.go
Labels: backport-to-v6.0.x, backport-to-v5.1.x

#2679 add check send enabled
  CHANGELOG.md
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/types/expected_keepers.go
Labels: backport-to-v6.0.x, backport-to-v2.5.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2685 Removing stale comment
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
Labels: backport-to-v6.0.x

#2692 removed unused variables
  modules/core/04-channel/keeper/handshake_test.go
  modules/core/04-channel/keeper/packet_test.go
Labels: automerge

#2647 deps: updating sdk to v0.46.4
  CHANGELOG.md
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
Labels: automerge, backport-to-v6.0.x, backport-to-v5.1.x

#2714 Update incorrect PR link in changelog regarding "check x/bank send enabled" fix
  CHANGELOG.md
Labels: backport-to-v6.0.x, backport-to-v2.5.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2723 e2e: fix memo test version declaration
  e2e/tests/transfer/base_test.go
Labels: automerge

#2662 chore: rm event emission after context caching
  modules/apps/27-interchain-accounts/host/keeper/relay.go
  modules/apps/29-fee/keeper/escrow.go
  modules/core/keeper/msg_server.go
Labels: backport-to-v6.0.x, backport-to-v5.1.x

#2740 docs: add missing set order functions for ICA
  docs/apps/interchain-accounts/integration.md
  docs/middleware/ics29-fee/integration.md
Labels: backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v3.3.x, backport-to-v4.1.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2737 docs: fix migration/docs for ICA controller middleware
  docs/apps/interchain-accounts/integration.md
  docs/middleware/ics29-fee/integration.md
  docs/migrations/v3-to-v4.md
Labels: backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v4.1.x, backport-to-v4.2.x, backport-to-v5.1.x

#2680 Update Compatibility tests to run against all unreleased versions
  .github/compatibility-test-matrices/unreleased/client.json
  .github/compatibility-test-matrices/unreleased/connection.json
  .github/compatibility-test-matrices/unreleased/incentivized-transfer.json
  .github/compatibility-test-matrices/unreleased/transfer.json
  .github/workflows/e2e-compatibility-workflow-call.yaml
  .github/workflows/e2e-compatibility.yaml
Labels: ci, e2e

#2697 Add git cliff toml to support generation of changelog
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  cliff.toml
Labels: backport-to-v2.4.x, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v3.3.x, backport-to-v4.1.x, backport-to-v2.5.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2741 fix: added check for empty path in 06-solomachine
  modules/light-clients/06-solomachine/client_state.go
  modules/light-clients/06-solomachine/client_state_test.go
Labels: automerge

#2784 deps: bump SDK to v0.46.6
  CHANGELOG.md
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
Labels: backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v5.1.x

#2786 Save gas on IsFeeEnabled
  CHANGELOG.md
  modules/apps/29-fee/keeper/keeper.go
Labels: backport-to-v6.0.x, backport-to-v4.1.x, backport-to-v4.2.x, backport-to-v5.2.x
