Repository cosmos/ibc-go, pull requests merged in 2022-10, with the labels that each got.

#2450 Renamed icatypes.PortPrefix to icatypes.ControllerPortPrefix
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/handshake.go
  modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/controller/keeper/migrations.go
  modules/apps/27-interchain-accounts/controller/keeper/migrations_test.go
  modules/apps/27-interchain-accounts/controller/migrations/v6/migrations_test.go
  modules/apps/27-interchain-accounts/genesis/types/genesis.go
  modules/apps/27-interchain-accounts/genesis/types/genesis_test.go
  modules/apps/27-interchain-accounts/host/client/cli/query.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/genesis.go
  modules/apps/27-interchain-accounts/host/keeper/genesis_test.go
  modules/apps/27-interchain-accounts/host/keeper/handshake.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/module.go
  modules/apps/27-interchain-accounts/module_test.go
  modules/apps/27-interchain-accounts/simulation/decoder_test.go
  modules/apps/27-interchain-accounts/simulation/genesis.go
  modules/apps/27-interchain-accounts/simulation/genesis_test.go
  modules/apps/27-interchain-accounts/types/keys.go
  modules/apps/27-interchain-accounts/types/port.go
  modules/apps/27-interchain-accounts/types/port_test.go
  modules/apps/29-fee/ica_test.go
Labels: backport-to-v6.0.x

#2377 MsgTransferResponse add sequence
  CHANGELOG.md
  docs/ibc/proto-docs.md
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/types/tx.pb.go
  proto/ibc/applications/transfer/v1/tx.proto
Labels: automerge, backport-to-v6.0.x, backport-to-v2.5.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2463 fix golangcli-lint complaint
  modules/core/23-commitment/types/merkle.go
Labels: automerge, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v5.1.x

#1703 Simplify SendPacket API
  CHANGELOG.md
  docs/ibc/apps.md
  docs/ibc/apps/ibcmodule.md
  docs/ibc/apps/packets_acks.md
  docs/ibc/middleware/develop.md
  docs/migrations/v5-to-v6.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/controller/keeper/relay.go
  modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
  modules/apps/27-interchain-accounts/host/keeper/keeper.go
  modules/apps/27-interchain-accounts/types/expected_keepers.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/keeper/keeper.go
  modules/apps/29-fee/keeper/relay.go
  modules/apps/29-fee/types/expected_keepers.go
  modules/apps/transfer/keeper/keeper.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/expected_keepers.go
  modules/core/04-channel/keeper/packet.go
  modules/core/04-channel/keeper/packet_test.go
  modules/core/04-channel/keeper/timeout_test.go
  modules/core/05-port/types/module.go
  testing/endpoint.go
Labels: automerge, backport-to-v6.0.x

#2479 chore: bump ibctest version and ibc-go version to v6 for e2e module
  e2e/go.mod
  e2e/go.sum
  e2e/testconfig/testconfig.go
  e2e/tests/core/client_test.go
  e2e/tests/interchain_accounts/base_test.go
  e2e/tests/interchain_accounts/incentivized_test.go
  e2e/tests/transfer/base_test.go
  e2e/tests/transfer/incentivized_test.go
  e2e/tests/upgrades/upgrade_test.go
  e2e/testsuite/grpc_query.go
  e2e/testsuite/relayer.go
  e2e/testsuite/testsuite.go
  e2e/testvalues/values.go
Labels: automerge

#2488 chore: fixing dead link to sdk v0.44 docs
  docs/migrations/v2-to-v3.md
Labels: backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v3.3.x, backport-to-v4.1.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2485 Add @damiannolan as full code owner of ibc-go
  .github/CODEOWNERS
Labels: automerge, backport-to-v6.0.x

#2511 chore: fix broken links
  .github/PULL_REQUEST_TEMPLATE.md
  docs/DOCS_README.md
  docs/apps/transfer/metrics.md
  docs/ibc/apps.md
  docs/ibc/apps/apps.md
  docs/ibc/integration.md
  docs/ibc/overview.md
  docs/ibc/relayer.md
  docs/middleware/ics29-fee/fee-distribution.md
Labels: backport-to-v2.1.x, backport-to-v2.2.x, backport-to-v2.3.x, backport-to-v2.4.x, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v3.3.x, backport-to-v4.1.x, backport-to-v2.5.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2446 refactor: remove SendTransfer, require IBC transfers to be initiated with MsgTransfer
  CHANGELOG.md
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
Labels: automerge, backport-to-v6.0.x

#2363 chore: update godocs for legacy apis on controller module
  e2e/tests/transfer/base_test.go
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/keeper/relay.go
Labels: backport-to-v6.0.x

#2417 docs: adding migration doc for ibc-go v6
  docs/migrations/v5-to-v6.md
Labels: backport-to-v6.0.x

#2567 chore: update tests to use new SendPacket API
  CHANGELOG.md
  modules/apps/29-fee/keeper/msg_server_test.go
  modules/core/03-connection/keeper/verify_test.go
  modules/core/04-channel/keeper/packet_test.go
  modules/core/04-channel/keeper/timeout_test.go
  modules/core/ante/ante_test.go
  modules/core/keeper/msg_server_test.go
  modules/light-clients/07-tendermint/client_state_test.go
  testing/endpoint.go
Labels: backport-to-v6.0.x

#2595 refactor: adapting transfer metadata bytes field to memo string
  CHANGELOG.md
  docs/ibc/proto-docs.md
  go.mod
  go.sum
  modules/apps/29-fee/transfer_test.go
  modules/apps/transfer/client/cli/tx.go
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/transfer_test.go
  modules/apps/transfer/types/events.go
  modules/apps/transfer/types/msgs.go
  modules/apps/transfer/types/msgs_test.go
  modules/apps/transfer/types/packet.go
  modules/apps/transfer/types/packet.pb.go
  modules/apps/transfer/types/packet_test.go
  modules/apps/transfer/types/tx.pb.go
  proto/ibc/applications/transfer/v1/tx.proto
  proto/ibc/applications/transfer/v2/packet.proto
Labels: backport-to-v6.0.x, backport-to-v2.5.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2568 use controller module address instead of module name for NewMsgChannelOpenInit
  modules/apps/27-interchain-accounts/controller/keeper/account.go
Labels: automerge, backport-to-v5.0.x, backport-to-v6.0.x, backport-to-v3.3.x, backport-to-v4.1.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2555 fix: forbid negative values for trusting period, unbonding period and max clock drift
  CHANGELOG.md
  modules/light-clients/07-tendermint/client_state.go
  modules/light-clients/07-tendermint/client_state_test.go
Labels: backport-to-v6.0.x, backport-to-v2.5.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2607 refactor!: allow for serialization of proto message without fulfillment of sdk.Msg interface
  CHANGELOG.md
  docs/apps/interchain-accounts/auth-modules.md
  docs/migrations/v5-to-v6.md
  modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
  modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
  modules/apps/27-interchain-accounts/controller/types/msgs_test.go
  modules/apps/27-interchain-accounts/host/client/cli/tx.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/relay_test.go
  modules/apps/27-interchain-accounts/types/codec.go
  modules/apps/27-interchain-accounts/types/codec_test.go
  modules/apps/29-fee/ica_test.go
Labels: automerge, backport-to-v6.0.x

#2628 fix e2e ica tests
  e2e/tests/interchain_accounts/base_test.go
  e2e/tests/interchain_accounts/groups_test.go
  e2e/tests/interchain_accounts/incentivized_test.go
Labels: backport-to-v6.0.x

#2573 rename `ClientParams` gRPC method to `Params`
  CHANGELOG.md
  docs/client/swagger-ui/swagger.yaml
  docs/ibc/proto-docs.md
  modules/core/02-client/client/cli/query.go
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/keeper/grpc_query_test.go
  modules/core/02-client/types/query.pb.go
  modules/core/02-client/types/query.pb.gw.go
  modules/core/keeper/grpc_query.go
  proto/ibc/core/client/v1/query.proto
Labels: backport-to-v6.0.x

#2590 remove port prefix requirement
  CHANGELOG.md
  modules/apps/27-interchain-accounts/host/keeper/handshake.go
  modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
Labels: backport-to-v6.0.x, backport-to-v4.2.x, backport-to-v5.1.x, backport-to-v3.4.x

#2601 fix: rm bech32 check from owner address on ICA controller msgs RegisterInterchainAccount and SendTx
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/controller/types/msgs_test.go
Labels: backport-to-v6.0.x
