Repository cosmos/ibc-go, pull requests merged in 2022-07, with the labels that each got.

#1627 deps: bumping go version 1.18
  .github/workflows/release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  Dockerfile
  go.mod
  go.sum
Labels: backport-to-v4.0.x

#1636 delete unused 04-channel version functions
  CHANGELOG.md
  modules/core/04-channel/types/version.go
  modules/core/04-channel/types/version_test.go
Labels: backport-to-v4.0.x

#1672 refactor: remove crossing hellos from 03-connection
  CHANGELOG.md
  docs/ibc/proto-docs.md
  docs/migrations/v3-to-v4.md
  modules/core/03-connection/keeper/handshake.go
  modules/core/03-connection/keeper/handshake_test.go
  modules/core/03-connection/types/tx.pb.go
  modules/core/03-connection/types/version.go
  modules/core/03-connection/types/version_test.go
  modules/core/keeper/msg_server.go
  proto/ibc/core/connection/v1/tx.proto
  testing/coordinator.go
Labels: backport-to-v4.0.x

#1695 remove spurious `TestABCICodeDeterminism` tests
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/types/ack_test.go
Labels: automerge, backport-to-v4.0.x

#1696 fix codeowners for 02-client
  .github/CODEOWNERS
Labels: automerge

#1639 docs: update middleware documentation
  docs/ibc/middleware/develop.md
  docs/ibc/middleware/integration.md
  modules/apps/29-fee/ibc_middleware.go
Labels: backport-to-v4.0.x

#1681 put back module name in `fungible_token_packet` event
  modules/apps/transfer/ibc_module.go
Labels: backport-to-v4.0.x

#1724 Remove leftover crossing hello tests in connection handshake
  modules/core/03-connection/keeper/handshake_test.go
Labels: backport-to-v4.0.x

#1675 Thomas/1584 update docs apps
  docs/.vuepress/config.js
  docs/ibc/apps/apps.md
  docs/ibc/apps/bindports.md
  docs/ibc/apps/ibcmodule.md
  docs/ibc/apps/keeper.md
  docs/ibc/apps/packets_acks.md
  docs/ibc/apps/routing.md
  docs/ibc/integration.md
  docs/ibc/middleware/develop.md
Labels: docs, backport-to-v4.0.x

#1665 update fee mw docs, add formating, fix typos, increase readability
  docs/.vuepress/config.js
  docs/assets/fee-mw/feeflow.png
  docs/assets/fee-mw/msgpaypacket.png
  docs/assets/fee-mw/paypacketfeeasync.png
  docs/assets/fee-mw/registerrelayeraddr.png
  docs/middleware/ics29-fee/end-users.md
  docs/middleware/ics29-fee/events.md
  docs/middleware/ics29-fee/fee-distribution.md
  docs/middleware/ics29-fee/msgs.md
  docs/middleware/ics29-fee/overview.md
Labels: docs, 29-fee

#1680 chore: denom traces migration handler
  CHANGELOG.md
  docs/migrations/support-denoms-with-slashes.md
  docs/migrations/v3-to-v4.md
  modules/apps/transfer/keeper/migrations.go
  modules/apps/transfer/keeper/migrations_test.go
  modules/apps/transfer/module.go
  modules/apps/transfer/types/trace.go
  modules/apps/transfer/types/trace_test.go
Labels: backport-to-v4.0.x, backport-to-v2.4.x, backport-to-v3.2.x

#1713 feat: allow governance to update the TrustingPeriod of the 07-tendermint light client
  CHANGELOG.md
  docs/architecture/adr-026-ibc-client-recovery-mechanisms.md
  docs/ibc/upgrades/developer-guide.md
  modules/light-clients/07-tendermint/types/proposal_handle.go
  modules/light-clients/07-tendermint/types/proposal_handle_test.go
Labels: backport-to-v4.0.x, backport-to-v2.4.x, backport-to-v3.2.x

#1774 fix: change non nil relayer check to non empty
  CHANGELOG.md
  modules/apps/29-fee/types/errors.go
  modules/apps/29-fee/types/fee.go
  modules/apps/29-fee/types/fee_test.go
  modules/apps/29-fee/types/msgs.go
  modules/apps/29-fee/types/msgs_test.go
Labels: backport-to-v4.0.x

#1740 fix: add cosmos_proto.implements_interface
  CHANGELOG.md
  modules/core/02-client/types/client.pb.go
  proto/ibc/core/client/v1/client.proto
Labels: backport-to-v3.0.x, backport-to-v2.1.x, backport-to-v2.2.x, backport-to-v2.3.x, backport-to-v3.1.x, backport-to-v4.0.x, backport-to-v2.4.x, backport-to-v3.2.x

#1792 fix: assert previous channel identifer is empty in Msg ValidateBasic
  CHANGELOG.md
  docs/migrations/v3-to-v4.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/core/04-channel/types/msgs.go
  modules/core/04-channel/types/msgs_test.go
  testing/endpoint.go
Labels: backport-to-v4.0.x

#1797 fix: assert previous connection id to be empty
  CHANGELOG.md
  docs/migrations/v3-to-v4.md
  modules/core/03-connection/types/msgs.go
  modules/core/03-connection/types/msgs_test.go
  testing/endpoint.go
Labels: backport-to-v4.0.x
