Repository cosmos/ibc-go, pull requests merged in 2022-03, with the labels that each got.

#1007 fix package import
  modules/apps/transfer/types/ack_test.go
Labels: backport-to-v3.0.x

#1035 feat: cli for query total recv fees
  modules/apps/29-fee/client/cli/cli.go
  modules/apps/29-fee/client/cli/query.go
Labels: automerge

#1057 chore: adding missing queries to cmd builder
  modules/apps/29-fee/client/cli/cli.go
Labels: automerge

#1016 small fixes for v2 to v3 migration
  docs/migrations/v2-to-v3.md
Labels: backport-to-v3.0.x

#1055 chore: update ics29 protodocs
  docs/ibc/proto-docs.md
  modules/apps/29-fee/types/ack.pb.go
  modules/apps/29-fee/types/fee.pb.go
  modules/apps/29-fee/types/genesis.pb.go
  modules/apps/29-fee/types/query.pb.go
  modules/apps/29-fee/types/tx.pb.go
  proto/ibc/applications/fee/v1/ack.proto
  proto/ibc/applications/fee/v1/fee.proto
  proto/ibc/applications/fee/v1/genesis.proto
  proto/ibc/applications/fee/v1/query.proto
  proto/ibc/applications/fee/v1/tx.proto
Labels: automerge

#995 call packet.GetSequence() rather than passing the func as argument
  CHANGELOG.md
  modules/core/04-channel/keeper/packet.go
Labels: automerge, backport-to-v1.1.x, backport-to-v1.2.x, backport-to-v2.0.x, backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x

#1073 deps: revert bump to SDK 0.45.1
  CHANGELOG.md
  go.mod
  go.sum
Labels: backport-to-v2.1.x

#1091 Fix ICA migration docs for upgrade proposal
  docs/migrations/v2-to-v3.md
Labels: backport-to-v3.0.x

#1094 fix: handle testing update client errors
  testing/coordinator.go
  testing/endpoint.go
  testing/path.go
Labels: automerge, backport-to-v3.0.x

#950 replace channel keeper with IBC keeper in AnteDecorator
  CHANGELOG.md
  docs/ibc/proto-docs.md
  docs/migrations/v2-to-v3.md
  modules/core/04-channel/types/tx.pb.go
  modules/core/ante/ante.go
  modules/core/ante/ante_test.go
  modules/core/keeper/msg_server.go
  proto/ibc/core/channel/v1/tx.proto
  testing/endpoint.go
  testing/simapp/ante_handler.go
  testing/simapp/app.go
Labels: backport-to-v3.0.x

#939 ibctesting: custom voting power reduction for testing
  CHANGELOG.md
  go.sum
  testing/app.go
  testing/chain.go
  testing/coordinator.go
  testing/endpoint.go
Labels: automerge, backport-to-v3.0.x

#1097 remove GetClientID from 07-tendermint misbehaviour
  CHANGELOG.md
  docs/ibc/proto-docs.md
  modules/light-clients/07-tendermint/types/misbehaviour.go
  modules/light-clients/07-tendermint/types/misbehaviour_test.go
  modules/light-clients/07-tendermint/types/tendermint.pb.go
  proto/ibc/lightclients/tendermint/v1/tendermint.proto
Labels: automerge

#1100 chore: remove GetClientID from 06-solomachine type Misbehaviour
  CHANGELOG.md
  docs/ibc/proto-docs.md
  modules/light-clients/06-solomachine/types/misbehaviour.go
  modules/light-clients/06-solomachine/types/misbehaviour_test.go
  modules/light-clients/06-solomachine/types/solomachine.pb.go
  proto/ibc/lightclients/solomachine/v2/solomachine.proto
Labels: automerge

#1120 fix: adjust InitModule to account for empty controller and host keepers
  docs/migrations/v2-to-v3.md
  modules/apps/27-interchain-accounts/module.go
  modules/apps/27-interchain-accounts/module_test.go
Labels: automerge, backport-to-v3.0.x

#1130 call packet.GetSequence() rather than passing the func as argument
  CHANGELOG.md
  modules/core/04-channel/keeper/packet.go
Labels: backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x, backport-to-v1.4.x, backport-to-v2.2.x

#1148 fixes for go-releaser configuration
  .github/workflows/release.yml
  .goreleaser.yml
Labels: backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x, backport-to-v1.4.x, backport-to-v2.2.x

#1151 Add alpha, beta, and rc release definitions
  RELEASES.md
Labels: automerge

#1172 fix typos in the controller params
  modules/apps/27-interchain-accounts/controller/keeper/params.go
Labels: automerge, backport-to-v3.0.x

#1175 add versions for new releases
  docs/.vuepress/config.js
  docs/versions
Labels: automerge, backport-to-v3.0.x

#1176 add version for v1.3
  docs/.vuepress/config.js
  docs/versions
Labels: automerge

#1177 add versions to v1.4
  docs/.vuepress/config.js
  docs/versions
Labels: automerge

#1178 add versions to v2.1
  docs/.vuepress/config.js
  docs/versions
Labels: automerge

#1179 add versions to v2.2
  docs/.vuepress/config.js
  docs/versions
Labels: automerge

#1144 chore: add solomachine client storage
  modules/light-clients/06-solomachine/types/misbehaviour_handle.go
  modules/light-clients/06-solomachine/types/update.go
  modules/light-clients/06-solomachine/types/update_test.go
Labels: automerge
