Repository cosmos/ibc-go, pull requests merged in 2022-01, with the labels that each got.

#692 improve 04-channel logging
  CHANGELOG.md
  modules/core/04-channel/keeper/packet.go
  modules/core/04-channel/keeper/timeout.go
Labels: automerge, backport-to-v1.1.x, backport-to-v1.2.x, backport-to-v2.0.x, backport-to-v3.0.x

#775 Replace github.com/pkg/errors with stdlib errors
  CHANGELOG.md
  go.mod
  modules/core/02-client/client/cli/tx.go
  modules/core/03-connection/client/utils/utils.go
Labels: automerge

#774 Fix for Evmos tests
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/ibc_module_test.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/types/account_test.go
  modules/apps/transfer/keeper/keeper_test.go
  modules/apps/transfer/transfer_test.go
  modules/core/02-client/abci_test.go
  modules/core/02-client/keeper/keeper_test.go
  modules/core/02-client/legacy/v100/store_test.go
  modules/core/02-client/types/msgs_test.go
  modules/core/03-connection/keeper/keeper_test.go
  modules/core/03-connection/types/msgs_test.go
  modules/core/04-channel/keeper/keeper_test.go
  modules/core/ante/ante_test.go
  modules/core/genesis_test.go
  modules/core/keeper/msg_server_test.go
  modules/core/legacy/v100/genesis_test.go
  modules/light-clients/06-solomachine/types/solomachine_test.go
  modules/light-clients/07-tendermint/types/tendermint_test.go
  testing/README.md
  testing/app.go
  testing/chain.go
  testing/coordinator.go
Labels: backport-to-v3.0.x

#794 refactor: construct ics27 error acknowledgement with determinstic ABCI code
  modules/apps/27-interchain-accounts/host/ibc_module.go
  modules/apps/27-interchain-accounts/host/types/ack.go
  modules/apps/27-interchain-accounts/host/types/ack_test.go
  modules/apps/27-interchain-accounts/types/errors.go
Labels: automerge

#810 add helper function in testing package: RecvPacketWithResult
  CHANGELOG.md
  testing/endpoint.go
  testing/events.go
  testing/path.go
Labels: automerge

#791 chore: use connection ID in interchain account store keys
  docs/ibc/proto-docs.md
  modules/apps/27-interchain-accounts/controller/keeper/account_test.go
  modules/apps/27-interchain-accounts/controller/keeper/genesis.go
  modules/apps/27-interchain-accounts/controller/keeper/genesis_test.go
  modules/apps/27-interchain-accounts/controller/keeper/handshake.go
  modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/controller/keeper/relay.go
  modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/account.go
  modules/apps/27-interchain-accounts/host/keeper/account_test.go
  modules/apps/27-interchain-accounts/host/keeper/genesis.go
  modules/apps/27-interchain-accounts/host/keeper/genesis_test.go
  modules/apps/27-interchain-accounts/host/keeper/handshake.go
  modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
  modules/apps/27-interchain-accounts/host/keeper/keeper.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/host/keeper/relay.go
  modules/apps/27-interchain-accounts/host/keeper/relay_test.go
  modules/apps/27-interchain-accounts/types/genesis.pb.go
  modules/apps/27-interchain-accounts/types/keys.go
  modules/apps/27-interchain-accounts/types/keys_test.go
  proto/ibc/applications/interchain_accounts/v1/genesis.proto
Labels: automerge

#790 chore: use host chain connection ID in address generation
  modules/apps/27-interchain-accounts/controller/ibc_module_test.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/handshake.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/types/account.go
  modules/apps/27-interchain-accounts/types/account_test.go
Labels: automerge
