Repository cosmos/ibc-go, pull requests merged in 2022-05, with the labels that each got.

#1341 check fee module locked and enable fee before refunding all fees
  CHANGELOG.md
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
Labels: automerge

#1355 override default docsBranch
  docs/.vuepress/config.js
Labels: automerge, backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x, backport-to-v1.4.x, backport-to-v2.2.x, backport-to-v1.5.x, backport-to-v2.3.x, backport-to-v3.1.x

#1402 add swagger for interchain accounts
  docs/client/config.json
  docs/client/swagger-ui/swagger.yaml
Labels: automerge, backport-to-v3.0.x, backport-to-v3.1.x

#1419 fix: ica controller middleware error typo
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
Labels: backport-to-v3.0.x, backport-to-v3.1.x

#1442 add actual parameter example to denom-trace and denom-hash CLI queries
  modules/apps/transfer/client/cli/query.go
Labels: backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x, backport-to-v1.4.x, backport-to-v2.2.x, backport-to-v1.5.x, backport-to-v2.3.x, backport-to-v3.1.x

#1464 Emit channel close event on ordered channel close
  CHANGELOG.md
  modules/core/04-channel/keeper/events.go
  modules/core/04-channel/keeper/timeout.go
  modules/core/04-channel/types/events.go
Labels: backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x, backport-to-v1.4.x, backport-to-v2.2.x, backport-to-v1.5.x, backport-to-v2.3.x, backport-to-v3.1.x
