Repository cosmos/ibc-go, pull requests merged in 2022-12, with the labels that each got.

#2868 chore: bump ics23 to v0.9.0
  CHANGELOG.md
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
Labels: backport-to-v2.4.x, backport-to-v6.0.x, backport-to-v3.3.x, backport-to-v4.1.x, backport-to-v2.5.x, backport-to-v4.2.x, backport-to-v3.4.x, backport-to-v5.2.x

#2859 fixes ICS27 `sendTx` cli command
  modules/apps/27-interchain-accounts/controller/client/cli/tx.go
Labels: backport-to-v6.0.x

#2942 fix: check `x/bank` send enabled before escrowing fees
  CHANGELOG.md
  modules/apps/29-fee/keeper/msg_server.go
  modules/apps/29-fee/keeper/msg_server_test.go
  modules/apps/29-fee/types/expected_keepers.go
Labels: backport-to-v5.2.x, backport-to-v4.3.x, backport-to-v6.1.x
