Repository cosmos/ibc-go, pull requests merged in 2022-08, with the labels that each got.

#1841 chore: delete gitpod.yml
  .gitpod.yml
Labels: backport-to-v5.0.x

#1882 fix(ics27): check packet data length explicitly over nil check
  CHANGELOG.md
  modules/apps/27-interchain-accounts/types/packet.go
  modules/apps/27-interchain-accounts/types/packet_test.go
Labels: backport-to-v4.0.x, backport-to-v3.2.x, backport-to-v5.0.x

#1905 Upgrade cosmos-sdk to v0.45.7
  CHANGELOG.md
  go.mod
  go.sum
  modules/core/03-connection/types/msgs_test.go
  modules/core/04-channel/types/msgs_test.go
  modules/core/23-commitment/types/commitment_test.go
Labels: backport-to-v2.4.x, backport-to-v3.2.x

#1923 chore: adding dockerfile and release task to release/2.1.x
  .github/workflows/release.yml
  Dockerfile
Labels: ci

#1928 chore: adding dockerfile and release task to release/3.0.x
  .github/workflows/release.yml
  Dockerfile
Labels: ci

#1925 chore: adding dockerfile and release task to release/2.3.x
  .github/workflows/release.yml
  Dockerfile
Labels: ci

#1931 chore: adding dockerfile and release task to release/3.1.x
  .github/workflows/release.yml
  Dockerfile
Labels: ci

#1924 chore: adding dockerfile and release task to release/2.2.x
  .github/workflows/release.yml
  Dockerfile
Labels: ci

#1907 fix: prevent blocked addresses from sending ICS 20 transfers
  CHANGELOG.md
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  testing/chain.go
Labels: backport-to-v4.0.x, backport-to-v2.4.x, backport-to-v3.2.x, backport-to-v5.0.x

#1932 chore: adding dockerfile and release task to release/3.2.x
  .github/workflows/release.yml
Labels: ci

#1865 ADR 007: Solo machine signature construction
  docs/architecture/adr-007-solomachine-signbytes.md
Labels: automerge

#1919 fix: "acknowledgement written" logs unsupported type
  CHANGELOG.md
  modules/core/04-channel/keeper/packet.go
Labels: backport-to-v3.0.x, backport-to-v2.1.x, backport-to-v2.2.x, backport-to-v2.3.x, backport-to-v3.1.x, backport-to-v4.0.x, backport-to-v2.4.x, backport-to-v3.2.x, backport-to-v5.0.x

#1985 feat: add channel query client to e2e test suite
  e2e/testsuite/grpc_query.go
  e2e/testsuite/testsuite.go
Labels: automerge

#1705 chore: update fee middleware docs to be more explicit about reasoning for removing invariant checks
  docs/middleware/ics29-fee/fee-distribution.md
Labels: backport-to-v4.0.x, backport-to-v5.0.x

#1973 feat(test): add successful e2e transfer test
  .github/workflows/e2e-manual.yaml
  e2e/testsuite/testsuite.go
  e2e/transfer_test.go
Labels: automerge

#2005 e2e: add 02-client query client
  e2e/testsuite/grpc_query.go
  e2e/testsuite/testsuite.go
Labels: automerge

#2024 Add interface for scoped keeper for 04-channel
  CHANGELOG.md
  modules/core/04-channel/keeper/keeper.go
  modules/core/04-channel/types/expected_keepers.go
Labels: automerge

#2025 Add scoped keeper interface for 05-port module
  CHANGELOG.md
  modules/core/05-port/keeper/keeper.go
  modules/core/05-port/types/expected_keepers.go
Labels: automerge

#2034 Add interface for scoped keeper for transfer module
  CHANGELOG.md
  modules/apps/transfer/keeper/keeper.go
  modules/apps/transfer/types/expected_keepers.go
Labels: automerge

#2065 fix: update simd gen accounts cmd to perform same functionality as SDK
  testing/simapp/simd/cmd/genaccounts.go
Labels: automerge, backport-to-v5.0.x

#2022 Update e2e go.mod
  e2e/go.mod
Labels: automerge

#2035 Add scoped keeper interface for interchain app
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/host/keeper/keeper.go
  modules/apps/27-interchain-accounts/types/expected_keepers.go
Labels: automerge

#2028 chore: set up IBCTestStakingKeeper interface
  CHANGELOG.md
  testing/README.md
  testing/app.go
  testing/chain_test.go
  testing/simapp/app.go
  testing/types/expected_keepers.go
Labels: backport-to-v5.0.x

#2068 chore: adding basic `Msg` service and `RegisterAccount` rpc boilerplate
  docs/ibc/proto-docs.md
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/types/codec.go
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/controller/types/tx.pb.go
  modules/apps/27-interchain-accounts/module.go
  modules/apps/27-interchain-accounts/types/codec.go
  proto/ibc/applications/interchain_accounts/controller/v1/tx.proto
Labels: automerge, backport-to-v5.1.x

#2079 Group indirect dependencies
  go.mod
Labels: automerge, backport-to-v5.0.x, backport-to-v5.1.x

#2058 Added interface to accept any type of ADR 031 message router.
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/host/keeper/keeper.go
  modules/apps/27-interchain-accounts/types/router.go
Labels: automerge, backport-to-v5.0.x, backport-to-v5.1.x

#2081 chore: adding `sdk.Msg` impl for ics27 `MsgRegisterAccount`
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/controller/types/msgs_test.go
  testing/values.go
Labels: backport-to-v5.1.x

#2076 chore: bump ibctest version
  e2e/fee_middleware_test.go
  e2e/go.mod
  e2e/go.sum
  e2e/interchain_accounts_test.go
  e2e/testsuite/testsuite.go
  e2e/testvalues/values.go
  e2e/transfer_test.go
Labels: automerge

#2112 feat: add genesis modification function to e2e
  e2e/testconfig/testconfig.go
  e2e/testvalues/values.go
Labels: automerge

#2123 add e2e for transfer send enabled param
  e2e/go.mod
  e2e/testconfig/testconfig.go
  e2e/testsuite/testsuite.go
  e2e/transfer_test.go
Labels: automerge

#2102 Add nil checks on the controller module for underlying app
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
Labels: backport-to-v5.1.x

#2086 chore: adding basic Msg service and SubmitTx rpc boilerplate
  docs/ibc/proto-docs.md
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/types/codec.go
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/controller/types/tx.pb.go
  proto/ibc/applications/interchain_accounts/controller/v1/tx.proto
Labels: backport-to-v5.1.x

#2144 testing: add base upgrade handler
  testing/simapp/app.go
  testing/simapp/upgrades/upgrades.go
Labels: automerge

#2136 Add cli for MsgRegisterAccount
  modules/apps/27-interchain-accounts/client/cli/cli.go
  modules/apps/27-interchain-accounts/controller/client/cli/tx.go
  modules/apps/27-interchain-accounts/module.go
Labels: automerge, backport-to-v5.1.x

#2146 chore: adapt ics27 controller claiming of channel capability
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/controller/keeper/relay.go
  modules/apps/27-interchain-accounts/controller/keeper/relay_test.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  testing/mock/ibc_module.go
Labels: backport-to-v5.1.x

#2148 fix: partial revert of #1942
  CHANGELOG.md
  modules/apps/29-fee/keeper/msg_server_test.go
  testing/chain.go
Labels: automerge, backport-to-v5.0.x, backport-to-v5.1.x

#2134 chore: ics27 channel capability migrations
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/migrations/v5/migrations.go
  modules/apps/27-interchain-accounts/controller/migrations/v5/migrations_test.go
Labels: automerge, backport-to-v5.1.x

#2159 Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS
  docs/package-lock.json
Labels: automerge

#2154 feat: add genesis simulation generation for ics27
  CHANGELOG.md
  modules/apps/27-interchain-accounts/module.go
  modules/apps/27-interchain-accounts/simulation/genesis.go
  modules/apps/27-interchain-accounts/simulation/genesis_test.go
Labels: automerge, backport-to-v5.0.x, backport-to-v5.1.x

#2157 chore: ics27 middleware callback routing
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/types/keys.go
  modules/apps/27-interchain-accounts/types/keys_test.go
Labels: automerge, backport-to-v5.1.x
