Repository cosmos/ibc-go, pull requests merged in 2022-06, with the labels that each got.

#1336 chore: Add consensus state heights query
  CHANGELOG.md
  docs/client/swagger-ui/swagger.yaml
  docs/ibc/proto-docs.md
  modules/core/02-client/client/cli/cli.go
  modules/core/02-client/client/cli/query.go
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/keeper/grpc_query_test.go
  modules/core/02-client/types/query.pb.go
  modules/core/02-client/types/query.pb.gw.go
  modules/core/keeper/grpc_query.go
  proto/ibc/core/client/v1/query.proto
Labels: backport-to-v1.5.x, backport-to-v2.3.x, backport-to-v3.1.x

#1432 feat: adding fee middleware support to ics27 interchain accounts
  CHANGELOG.md
  docs/migrations/v3-to-v4.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/account_test.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  testing/simapp/app.go
Labels: automerge

#1433 test: adding fee middleware tests for ics27 interchain accounts
  modules/apps/27-interchain-accounts/types/metadata.go
  modules/apps/29-fee/ica_test.go
Labels: automerge

#1511 fix: deprecate AllowUpdateAfter...check
  CHANGELOG.md
  docs/architecture/adr-026-ibc-client-recovery-mechanisms.md
  docs/ibc/proposals.md
  docs/ibc/proto-docs.md
  modules/light-clients/07-tendermint/types/proposal_handle.go
  modules/light-clients/07-tendermint/types/proposal_handle_test.go
  modules/light-clients/07-tendermint/types/tendermint.pb.go
  proto/ibc/lightclients/tendermint/v1/tendermint.proto
Labels: backport-to-v1.5.x, backport-to-v2.3.x, backport-to-v3.1.x

#1544 add migration for base denoms with slashes to docs site
  docs/.vuepress/config.js
Labels: automerge, backport-to-v1.5.x, backport-to-v2.3.x, backport-to-v3.1.x

#1567 docs: ics29 middleware usage for app devs
  docs/.vuepress/config.js
  docs/middleware/ics29-fee/integration.md
Labels: automerge

#1573 fix typo in parameter name of `NewDefaultMetadata`
  modules/apps/27-interchain-accounts/types/metadata.go
Labels: automerge

#1577 docs: payee registration and fee distribution for relayer operators
  docs/.vuepress/config.js
  docs/middleware/ics29-fee/fee-distribution.md
Labels: automerge

#1580 chore: add module name to incentivized packet events
  modules/apps/29-fee/keeper/events.go
Labels: automerge

#1570 feat: emitting an event when handling a client upgrade proposal
  CHANGELOG.md
  modules/core/02-client/keeper/events.go
  modules/core/02-client/keeper/proposal.go
  modules/core/02-client/types/events.go
Labels: backport-to-v3.0.x, backport-to-v1.3.x, backport-to-v2.1.x, backport-to-v1.4.x, backport-to-v2.2.x, backport-to-v1.5.x, backport-to-v2.3.x, backport-to-v3.1.x
