Repository cosmos/ibc-go, pull requests merged in 2023-04, with the labels that each got.

#3372 Prevent e2e from running on merge to main
  .github/workflows/e2e.yaml
Labels: needs discussion

#3439 nit: Use nil pointer pattern to check for interface compliance.
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/keeper/grpc_query.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/host/keeper/grpc_query.go
  modules/apps/27-interchain-accounts/module.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/keeper/grpc_query.go
  modules/apps/29-fee/keeper/keeper.go
  modules/apps/29-fee/keeper/msg_server.go
  modules/apps/29-fee/module.go
  modules/apps/transfer/keeper/grpc_query.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/module.go
  modules/apps/transfer/types/trace.go
  modules/apps/transfer/types/transfer_authorization.go
  modules/capability/module.go
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/migrations/v7/solomachine.go
  modules/core/02-client/types/client.go
  modules/core/02-client/types/genesis.go
  modules/core/02-client/types/msgs.go
  modules/core/02-client/types/proposal.go
  modules/core/02-client/types/query.go
  modules/core/03-connection/keeper/grpc_query.go
  modules/core/03-connection/types/msgs.go
  modules/core/03-connection/types/query.go
  modules/core/03-connection/types/version.go
  modules/core/04-channel/keeper/keeper.go
  modules/core/04-channel/types/msgs.go
  modules/core/04-channel/types/query.go
  modules/core/keeper/msg_server.go
  modules/core/module.go
  modules/core/types/genesis.go
  modules/light-clients/06-solomachine/consensus_state.go
  modules/light-clients/06-solomachine/header.go
  modules/light-clients/06-solomachine/misbehaviour.go
  modules/light-clients/06-solomachine/module.go
  modules/light-clients/06-solomachine/solomachine.go
  modules/light-clients/07-tendermint/header.go
  modules/light-clients/07-tendermint/misbehaviour.go
  modules/light-clients/07-tendermint/module.go
Labels: code hygiene

#3457 deps: bump ics23 v0.10.0
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
  modules/capability/go.mod
  modules/capability/go.sum
Labels: backport-to-v7.1.x, backport-to-v5.3.x, backport-to-v6.2.x, backport-to-v4.4.x

#3436 Replace initialization with declaration in grpc query handlers
  modules/apps/transfer/keeper/grpc_query.go
  modules/apps/transfer/keeper/grpc_query_test.go
  modules/core/02-client/keeper/grpc_query.go
  modules/core/03-connection/keeper/grpc_query.go
  modules/core/04-channel/keeper/grpc_query.go
  modules/core/04-channel/keeper/grpc_query_test.go
Labels: automerge

#3019 Chore: Make a state entry to find total amount of native assets IBC'd out
  .github/workflows/e2e-upgrade.yaml
  e2e/go.mod
  e2e/tests/transfer/base_test.go
  e2e/tests/upgrades/upgrade_test.go
  e2e/testsuite/grpc_query.go
  modules/apps/transfer/client/cli/cli.go
  modules/apps/transfer/client/cli/query.go
  modules/apps/transfer/keeper/genesis.go
  modules/apps/transfer/keeper/genesis_test.go
  modules/apps/transfer/keeper/grpc_query.go
  modules/apps/transfer/keeper/grpc_query_test.go
  modules/apps/transfer/keeper/keeper.go
  modules/apps/transfer/keeper/keeper_test.go
  modules/apps/transfer/keeper/migrations.go
  modules/apps/transfer/keeper/migrations_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/module.go
  modules/apps/transfer/types/expected_keepers.go
  modules/apps/transfer/types/genesis.go
  modules/apps/transfer/types/genesis.pb.go
  modules/apps/transfer/types/keys.go
  modules/apps/transfer/types/query.pb.go
  modules/apps/transfer/types/query.pb.gw.go
  modules/apps/transfer/types/trace.go
  proto/ibc/applications/transfer/v1/genesis.proto
  proto/ibc/applications/transfer/v1/query.proto
  proto/ibc/applications/transfer/v1/transfer.proto
Labels: backport-to-v7.1.x

#3498 Cleanup unused functions (Channel upgradability)
  modules/core/04-channel/client/cli/cli.go
  modules/core/04-channel/client/cli/query.go
  modules/core/04-channel/client/utils/utils.go
  modules/core/04-channel/keeper/grpc_query.go
  modules/core/04-channel/keeper/grpc_query_test.go
  modules/core/04-channel/keeper/keeper.go
  modules/core/04-channel/keeper/keeper_test.go
  modules/core/04-channel/types/query.go
  modules/core/keeper/grpc_query.go
  proto/ibc/core/channel/v1/query.proto
Labels: 04-channel

#3459 deps: bump SDK to v0.47.1
  e2e/go.mod
  e2e/go.sum
  e2e/testsuite/tx.go
  go.mod
  go.sum
  modules/capability/go.mod
  modules/capability/go.sum
Labels: backport-to-v7.1.x
