Repository cosmos/ibc-go, pull requests merged in 2023-01, with the labels that each got.

#2974 docs: adding export metadata docs for light client module genesis
  docs/ibc/light-clients/genesis.md
Labels: automerge

#2973 chore: write channel state before invoking app callbacks in ack and confirm channel handshake steps
  modules/core/keeper/msg_server.go
Labels: backport-to-v4.3.x

#3044 docs: add documentation for `TransferAuthorization`
  docs/.vuepress/config.js
  docs/apps/transfer/authorizations.md
Labels: backport-to-v7.0.x

#3045 fix: allow value with slashes in URL template
  modules/apps/transfer/types/query.pb.go
  modules/apps/transfer/types/query.pb.gw.go
  proto/ibc/applications/transfer/v1/query.proto
Labels: backport-to-v7.0.x

#3046 fix: moved non-verification misbehaviour checks to checkForMisbehaviour
  CHANGELOG.md
  modules/light-clients/07-tendermint/misbehaviour_handle.go
  modules/light-clients/07-tendermint/misbehaviour_handle_test.go
  modules/light-clients/07-tendermint/update_test.go
Labels: backport-to-v7.0.x
