Repository cosmos/ibc-go, pull requests merged in 2023-03, with the labels that each got.

#3258 chore: update changelog
  CHANGELOG.md
Labels: backport-to-v7.0.x

#3278 fix: e2e script defaults
  e2e/scripts/run-e2e.sh
Labels: automerge

#3283 Update v6-to-v7.md
  docs/migrations/v6-to-v7.md
Labels: automerge, backport-to-v7.0.x

#3227 remove query client
  modules/apps/29-fee/keeper/grpc_query_test.go
  modules/apps/29-fee/keeper/keeper_test.go
  modules/apps/transfer/keeper/grpc_query_test.go
  modules/apps/transfer/keeper/keeper_test.go
  modules/core/02-client/keeper/grpc_query_test.go
  modules/core/02-client/keeper/keeper_test.go
Labels: automerge

#3253 Rename ``IsBound`` to ``HasCapability``
  docs/ibc/apps.md
  docs/ibc/apps/bindports.md
  docs/ibc/apps/keeper.md
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/genesis.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/host/keeper/genesis.go
  modules/apps/27-interchain-accounts/host/keeper/keeper.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  modules/apps/transfer/keeper/genesis.go
  modules/apps/transfer/keeper/keeper.go
Labels: automerge

#3293 chore: fix dead links
  .github/PULL_REQUEST_TEMPLATE.md
  docs/dev/project-structure.md
  docs/ibc/integration.md
Labels: automerge

#3295 deps: bump SDK v0.47
  CHANGELOG.md
  e2e/dockerutil/dockerutil.go
  e2e/go.mod
  e2e/go.sum
  e2e/testsuite/diagnostics/diagnostics.go
  e2e/testsuite/events.go
  e2e/testsuite/grpc_query.go
  go.mod
  go.sum
  modules/apps/27-interchain-accounts/module_test.go
  modules/core/02-client/abci_test.go
  testing/README.md
  testing/app.go
  testing/endpoint.go
  testing/simapp/sim_bench_test.go
  testing/simapp/sim_test.go
  testing/simapp/simd/cmd/root.go
Labels: backport-to-v7.0.x, backport-to-v7.1.x

#3313 E2E fzf Test Selection Autocompletion
  e2e/README.md
  e2e/scripts/run-e2e.sh
Labels: improvement, e2e
