Repository cosmos/ibc-go, pull requests merged in 2023-05, with the labels that each got.

#3542 deps: bump sdk to v0.47.2 and cometbft to v0.37.1
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
  modules/capability/go.mod
  modules/capability/go.sum
Labels: backport-to-v7.1.x

#3517 Fix escrow proto E2E
  e2e/tests/transfer/base_test.go
  e2e/testsuite/grpc_query.go
  modules/apps/transfer/keeper/genesis.go
  modules/apps/transfer/keeper/genesis_test.go
  modules/apps/transfer/keeper/grpc_query.go
  modules/apps/transfer/keeper/grpc_query_test.go
  modules/apps/transfer/keeper/keeper.go
  modules/apps/transfer/keeper/keeper_test.go
  modules/apps/transfer/keeper/migrations.go
  modules/apps/transfer/keeper/migrations_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/query.pb.go
  proto/ibc/applications/transfer/v1/query.proto
Labels: backport-to-v7.1.x

#3454 imp: represent unlimited approvals with MaxUint256 value
  CHANGELOG.md
  docs/apps/transfer/authorizations.md
  e2e/tests/core/client_test.go
  e2e/testsuite/grpc_query.go
  modules/apps/transfer/types/transfer_authorization.go
  modules/apps/transfer/types/transfer_authorization_test.go
Labels: backport-to-v7.1.x, backport-to-v6.2.x

#3515 docs: Add docs to Acknowledgement.Success
  modules/core/exported/channel.go
Labels: automerge

#3586 chore: transfer authz nits
  modules/apps/transfer/types/transfer_authorization.go
  modules/apps/transfer/types/transfer_authorization_test.go
Labels: backport-to-v7.1.x, backport-to-v6.2.x

#3593 fix(statemachine)!: update error returned in 04-channel SendPacket
  modules/core/04-channel/keeper/packet.go
Labels: backport-to-v7.1.x

#3587 fix: add relative timeout support for localhost clients using the transfer CLI client
  modules/apps/transfer/client/cli/tx.go
Labels: backport-to-v7.1.x

#3706 fix: fix invalid seq tests
  modules/core/04-channel/keeper/grpc_query_test.go
Labels: automerge
