Repository cosmos/ibc-go, pull requests merged in 2023-02, with the labels that each got.

#3027 followup from review comments for #2709
  modules/apps/27-interchain-accounts/doc.go
  modules/apps/29-fee/doc.go
  modules/apps/transfer/doc.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/core/02-client/doc.go
  modules/core/03-connection/doc.go
  modules/core/04-channel/doc.go
  modules/core/05-port/doc.go
  modules/core/24-host/doc.go
  modules/core/keeper/keeper_test.go
  modules/light-clients/06-solomachine/doc.go
  modules/light-clients/07-tendermint/doc.go
  testing/simapp/params/doc.go
Labels: automerge

#3079 feat: add authz support for ics20
  .github/workflows/e2e-manual-simd.yaml
  docs/ibc/proto-docs.md
  e2e/testconfig/testconfig.go
  e2e/tests/transfer/authz_test.go
  e2e/testsuite/codec.go
  e2e/testsuite/testsuite.go
  e2e/testvalues/values.go
  go.mod
  modules/apps/transfer/types/authz.pb.go
  modules/apps/transfer/types/codec.go
  modules/apps/transfer/types/errors.go
  modules/apps/transfer/types/transfer_authorization.go
  modules/apps/transfer/types/transfer_authorization_test.go
  modules/apps/transfer/types/types_test.go
  proto/ibc/applications/transfer/v1/authz.proto
Labels: backport-to-v7.0.x

#3080 chores: post v4.3.0 release chores
  .github/compatibility-test-matrices/release-v4.3.x/incentivized-transfer-chain-a.json
  .github/compatibility-test-matrices/release-v4.3.x/incentivized-transfer-chain-b.json
  .github/compatibility-test-matrices/release-v4.3.x/transfer-chain-a.json
  .github/compatibility-test-matrices/release-v4.3.x/transfer-chain-b.json
  .github/compatibility-test-matrices/release-v5.2.x/incentivized-transfer-chain-a.json
  .github/compatibility-test-matrices/release-v5.2.x/incentivized-transfer-chain-b.json
  .github/compatibility-test-matrices/release-v5.2.x/transfer-chain-a.json
  .github/compatibility-test-matrices/release-v5.2.x/transfer-chain-b.json
  .github/compatibility-test-matrices/release-v6.1.x/client-chain-a.json
  .github/compatibility-test-matrices/release-v6.1.x/client-chain-b.json
  .github/compatibility-test-matrices/release-v6.1.x/connection-chain-a.json
  .github/compatibility-test-matrices/release-v6.1.x/connection-chain-b.json
  .github/compatibility-test-matrices/release-v6.1.x/incentivized-transfer-chain-a.json
  .github/compatibility-test-matrices/release-v6.1.x/incentivized-transfer-chain-b.json
  .github/compatibility-test-matrices/release-v6.1.x/transfer-chain-a.json
  .github/compatibility-test-matrices/release-v6.1.x/transfer-chain-b.json
  .github/compatibility-test-matrices/release-v7.0.x/client-chain-a.json
  .github/compatibility-test-matrices/release-v7.0.x/client-chain-b.json
  .github/compatibility-test-matrices/release-v7.0.x/connection-chain-a.json
  .github/compatibility-test-matrices/release-v7.0.x/connection-chain-b.json
  .github/compatibility-test-matrices/release-v7.0.x/incentivized-transfer-chain-a.json
  .github/compatibility-test-matrices/release-v7.0.x/incentivized-transfer-chain-b.json
  .github/compatibility-test-matrices/release-v7.0.x/transfer-chain-a.json
  .github/compatibility-test-matrices/release-v7.0.x/transfer-chain-b.json
  .github/workflows/e2e-manual-icad.yaml
  .github/workflows/e2e-manual-simd.yaml
  .github/workflows/e2e-upgrade.yaml
  RELEASES.md
  docs/.vuepress/config.js
  docs/versions
Labels: automerge

#3113 chore: set light client module names
  e2e/go.mod
  go.mod
  modules/light-clients/06-solomachine/keys.go
  modules/light-clients/07-tendermint/keys.go
Labels: backport-to-v7.0.x

#3117 imp: adding channelID to `MsgChannelOpenTryResponse`
  modules/core/04-channel/types/tx.pb.go
  modules/core/keeper/msg_server.go
  proto/ibc/core/channel/v1/tx.proto
Labels: backport-to-v7.1.x

#3135 docs: add link to BSR for proto docs
  docs/ibc/proto-docs.md
Labels: backport-to-v7.0.x

#3136 fix: simapp and upgrade configuration for e2e v7 upgrade
  .github/workflows/e2e-upgrade.yaml
  e2e/scripts/run-e2e.sh
  testing/simapp/app.go
  testing/simapp/upgrades/v7/upgrades.go
Labels: backport-to-v7.0.x

#3107 docs: adding migration doc info for sdk v0.47
  docs/migrations/v6-to-v7.md
Labels: backport-to-v7.0.x, backport-to-v7.1.x

#3149 chore: remove legacy interface function, RandomizedParams, which is no longer used
  CHANGELOG.md
  modules/apps/27-interchain-accounts/module.go
  modules/apps/27-interchain-accounts/simulation/params.go
  modules/apps/27-interchain-accounts/simulation/params_test.go
  modules/apps/29-fee/module.go
  modules/apps/transfer/module.go
  modules/apps/transfer/simulation/params.go
  modules/apps/transfer/simulation/params_test.go
  modules/core/module.go
Labels: backport-to-v7.0.x, backport-to-v7.1.x

#3154 chore: remove unused ProposalContents function
  CHANGELOG.md
  modules/apps/27-interchain-accounts/module.go
  modules/apps/29-fee/module.go
  modules/apps/transfer/module.go
  modules/core/module.go
Labels: backport-to-v7.0.x, backport-to-v7.1.x

#3165 chore: use fully qualified typeURL interface names in protos
  go.mod
  modules/apps/27-interchain-accounts/types/account.pb.go
  proto/ibc/applications/interchain_accounts/v1/account.proto
Labels: backport-to-v7.0.x

#3182 chore: removing legacy params subspaces for sdk modules
  testing/simapp/app.go
Labels: backport-to-v7.1.x

#3204 Dang/add port id into msg register interchain account response
  docs/apps/interchain-accounts/messages.md
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/types/tx.pb.go
  proto/ibc/applications/interchain_accounts/controller/v1/tx.proto
Labels: backport-to-v7.1.x
