Repository cosmos/ibc-go, pull requests merged in 2024-08, with the labels that each got.

#7006 chore: move status checks from connection verify_* functions to 02-client verify_* functions.
  modules/core/02-client/keeper/keeper.go
  modules/core/02-client/keeper/keeper_test.go
  modules/core/03-connection/keeper/verify.go
Labels: feat/ibc-eureka

#7007 chore: split out packet handling rpcs
  modules/core/04-channel/types/codec.go
  modules/core/04-channel/types/tx.pb.go
  modules/core/keeper/msg_server.go
  modules/core/module.go
  modules/core/packet-server/keeper/keeper.go
  modules/core/packet-server/types/expected_keepers.go
  modules/core/packet-server/types/merkle.go
  proto/ibc/core/channel/v1/tx.proto
Labels: feat/ibc-eureka

#6986 Add versions to packet and create Eureka packet commitment
  modules/apps/29-fee/ica_test.go
  modules/core/03-connection/keeper/verify_test.go
  modules/core/04-channel/keeper/packet.go
  modules/core/04-channel/keeper/packet_test.go
  modules/core/04-channel/keeper/timeout.go
  modules/core/04-channel/types/channel.pb.go
  modules/core/04-channel/types/msgs_test.go
  modules/core/04-channel/types/packet.go
  modules/core/04-channel/types/packet_test.go
  modules/light-clients/06-solomachine/light_client_module_test.go
  modules/light-clients/07-tendermint/light_client_module_test.go
  modules/light-clients/09-localhost/light_client_module_test.go
  proto/ibc/core/channel/v1/channel.proto
  testing/path.go
  testing/solomachine.go
Labels: feat/ibc-eureka

#7000 Supply app version to contract keeper
  docs/architecture/adr-008-app-caller-cbs.md
  docs/docs/04-middleware/02-callbacks/03-interfaces.md
  docs/docs/05-migrations/13-v8-to-v9.md
  modules/apps/callbacks/CHANGELOG.md
  modules/apps/callbacks/fee_transfer_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/replay_test.go
  modules/apps/callbacks/testing/simapp/contract_keeper.go
  modules/apps/callbacks/types/callbacks.go
  modules/apps/callbacks/types/callbacks_test.go
  modules/apps/callbacks/types/events.go
  modules/apps/callbacks/types/events_test.go
  modules/apps/callbacks/types/expected_keepers.go
  modules/apps/callbacks/types/export_test.go
Labels: priority

#7009 (chore): remove capabilities from channel handsake
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/controller/keeper/handshake.go
  modules/apps/27-interchain-accounts/controller/keeper/handshake_test.go
  modules/apps/27-interchain-accounts/controller/keeper/migrations_test.go
  modules/apps/27-interchain-accounts/controller/migrations/v6/migrations_test.go
  modules/apps/27-interchain-accounts/host/ibc_module.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/handshake.go
  modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/ibc_module_test.go
  modules/core/04-channel/keeper/handshake.go
  modules/core/04-channel/keeper/handshake_test.go
  modules/core/05-port/keeper/keeper.go
  modules/core/05-port/types/module.go
  modules/core/ante/ante.go
  modules/core/ante/ante_test.go
  modules/core/keeper/msg_server.go
  modules/core/keeper/msg_server_test.go
  simapp/app.go
  testing/mock/ibc_app.go
  testing/mock/ibc_module.go
  testing/mock/middleware.go
Labels: priority, feat/port-router

#7010 Adding updates to composite router and scaffolding for LegacyIBCModule
  modules/apps/callbacks/ibc_middleware_test.go
  modules/core/05-port/keeper/keeper.go
  modules/core/05-port/types/ibc_legacy_module.go
  modules/core/05-port/types/router.go
  modules/core/05-port/types/router_v2.go
  modules/core/keeper/keeper.go
Labels: priority, feat/port-router

#7059 Add Wrap/Unwrap Interfaces and implement OnChanOpenInit
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/callbacks/testing/simapp/app.go
  modules/core/05-port/types/ibc_legacy_module.go
  modules/core/05-port/types/module.go
  modules/core/05-port/types/router_v2.go
  modules/core/keeper/msg_server.go
  simapp/app.go
  testing/simapp/app.go
Labels: priority, feat/port-router

#7067 Use new port router for onchanupgradetry
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/29-fee/fee_test.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/callbacks/testing/simapp/app.go
  modules/apps/transfer/ibc_module_test.go
  modules/core/05-port/types/ibc_legacy_module.go
  modules/core/keeper/msg_server.go
  testing/simapp/app.go
Labels: priority, feat/port-router

#7082 Use new port router for OnChanUpgradeInit
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware.go
  modules/core/05-port/types/ibc_legacy_module.go
  modules/core/keeper/msg_server.go
  modules/core/keeper/msg_server_test.go
Labels: priority, feat/port-router

#7095 refactor: implement OnChanCloseInit using new port router.
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/core/05-port/types/ibc_legacy_module.go
  modules/core/keeper/msg_server.go
Labels: priority, feat/port-router

#7096 refactor: implement OnChanCloseConfirm using new port router
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/core/05-port/types/ibc_legacy_module.go
  modules/core/keeper/msg_server.go
Labels: priority, feat/port-router

#7093 refactor: replace ack interface with result type for OnRecvPacket
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/controller/keeper/events.go
  modules/apps/27-interchain-accounts/host/ibc_module.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/events.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
  modules/apps/29-fee/keeper/relay.go
  modules/apps/29-fee/keeper/relay_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/callbacks/replay_test.go
  modules/apps/callbacks/testing/simapp/contract_keeper.go
  modules/apps/callbacks/types/expected_keepers.go
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/keeper/forwarding.go
  modules/core/03-connection/keeper/verify_test.go
  modules/core/04-channel/keeper/packet.go
  modules/core/04-channel/keeper/packet_test.go
  modules/core/05-port/types/ibc_legacy_module.go
  modules/core/05-port/types/module.go
  modules/core/ante/ante_test.go
  modules/core/exported/packet.go
  modules/core/keeper/msg_server.go
  testing/endpoint.go
  testing/mock/ibc_app.go
  testing/mock/ibc_module.go
  testing/mock/middleware.go
Labels: priority

#7110 imp (api)!: convert coins to token only once in MsgTransfer
  modules/apps/transfer/keeper/export_test.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
Labels: feat/port-router

#7109 feat(eureka): fix condition in commit packet, added test for zero timeout height
  modules/core/02-client/keeper/keeper.go
  modules/core/02-client/types/client.go
  modules/core/02-client/types/errors.go
  modules/core/04-channel/types/packet.go
  modules/core/04-channel/types/packet_test.go
  modules/core/keeper/msg_server.go
  modules/core/packet-server/keeper/keeper.go
Labels: feat/ibc-eureka

#6905 test: add unwind + forwarding to sender test
  modules/apps/transfer/keeper/relay_forwarding_test.go
  modules/apps/transfer/types/forwarding_test.go
  testing/events.go
Labels: priority

#7129 backport-v8.5.x: self client/consensus state removal from connection handshake
  CHANGELOG.md
  go.mod
  modules/core/03-connection/keeper/handshake.go
  modules/core/03-connection/keeper/handshake_test.go
  modules/core/03-connection/types/msgs.go
  modules/core/03-connection/types/msgs_test.go
  modules/core/03-connection/types/tx.pb.go
  modules/core/keeper/msg_server.go
  proto/ibc/core/connection/v1/tx.proto
  testing/solomachine.go
Labels: priority

#7128 backport-v7.8.x: self client/consensus state removal from connection handshake
  CHANGELOG.md
  modules/core/03-connection/keeper/handshake.go
  modules/core/03-connection/keeper/handshake_test.go
  modules/core/03-connection/types/msgs.go
  modules/core/03-connection/types/msgs_test.go
  modules/core/03-connection/types/tx.pb.go
  modules/core/keeper/msg_server.go
  proto/ibc/core/connection/v1/tx.proto
  testing/solomachine.go
Labels: priority

#7130 revert: accidental change of consensus height to pointer
  modules/core/03-connection/types/tx.pb.go
  proto/ibc/core/connection/v1/tx.proto
Labels: priority, backport-to-v9.0.x

#7144 Bznein/7023/on timeout packet
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/keeper/relay_forwarding_test.go
  modules/core/05-port/types/ibc_legacy_module.go
  modules/core/keeper/msg_server.go
Labels: priority, feat/port-router

#7149 imp: reduce channel lookup in timeout flow
  modules/core/04-channel/keeper/export_test.go
  modules/core/04-channel/keeper/timeout.go
  modules/core/04-channel/keeper/timeout_test.go
Labels: feat/ibc-eureka

#7142 Add convenience func to reverse callbacks and refactor other methods
  modules/core/05-port/types/ibc_legacy_module.go
Labels: priority, feat/port-router

#7164 Use app router in OnTimeoutPacket handler
  modules/core/keeper/msg_server.go
Labels: priority, feat/port-router

#7146 imp: require stricter usage of app version in packet
  modules/core/04-channel/types/packet.go
  modules/core/04-channel/types/packet_test.go
Labels: feat/ibc-eureka

#7155 chore: remove unnecessary comments
  modules/core/packet-server/keeper/keeper.go
Labels: feat/ibc-eureka

#7160 imp: add tests for BuildMerklePath, make merkle path non-nullable in counterparty
  modules/core/02-client/keeper/keeper_test.go
  modules/core/02-client/types/client.go
  modules/core/02-client/types/client.pb.go
  modules/core/02-client/types/client_test.go
  modules/core/02-client/types/msgs.go
  modules/core/keeper/msg_server_test.go
  modules/core/packet-server/types/merkle.go
  modules/core/packet-server/types/merkle_test.go
  proto/ibc/core/client/v1/client.proto
  testing/endpoint.go
Labels: feat/ibc-eureka

#7156 chore: add godoc to packet server handlers
  modules/core/packet-server/keeper/keeper.go
Labels: feat/ibc-eureka

#7179 feat(eureka): add tests for `MsgProvideCounterparty`
  modules/core/02-client/keeper/keeper_test.go
  modules/core/02-client/types/msgs_test.go
Labels: feat/ibc-eureka

#7113 docs: update transfer cli docs
  docs/docs/02-apps/01-transfer/09-client.md
  modules/apps/transfer/client/cli/tx.go
Labels: backport-to-v9.0.x

#7196 add submodule to logger
  modules/core/packet-server/keeper/keeper.go
  modules/core/packet-server/types/keys.go
Labels: feat/ibc-eureka

#7162 tests: msg server tests for eureka
  modules/core/keeper/msg_server_test.go
Labels: feat/ibc-eureka

#7193 Validate MerklePathPrefix and Path
  modules/core/02-client/types/client.go
  modules/core/02-client/types/client_test.go
  modules/core/23-commitment/types/v2/merkle.go
  modules/core/23-commitment/types/v2/merkle_test.go
Labels: feat/ibc-eureka

#7213 chore (api)!: remove capabilities from SendPacket
  CHANGELOG.md
  docs/docs/05-migrations/14-v9-to-v10.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/keeper/relay.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/keeper/relay.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/core/04-channel/keeper/packet.go
  modules/core/04-channel/keeper/packet_test.go
  modules/core/05-port/types/module.go
  testing/endpoint.go
  testing/mock/middleware.go
Labels: priority

#7224 deps: bump ics23 to v0.11.0
  CHANGELOG.md
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
  modules/apps/callbacks/go.mod
  modules/apps/callbacks/go.sum
  modules/light-clients/08-wasm/go.mod
  modules/light-clients/08-wasm/go.sum
  simapp/go.mod
  simapp/go.sum
Labels: priority, backport-to-v9.0.x

#7225 chore (api)!: remove capabilities from WriteAcknowledgement
  CHANGELOG.md
  docs/docs/05-migrations/14-v9-to-v10.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/keeper/relay.go
  modules/apps/29-fee/keeper/relay_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/keeper/forwarding.go
  modules/core/04-channel/keeper/packet.go
  modules/core/04-channel/keeper/packet_test.go
  modules/core/05-port/types/module.go
  modules/core/keeper/msg_server.go
  testing/endpoint.go
  testing/mock/middleware.go
Labels: priority

#7222 deps(release/v8.5.x): bump ics23 to v0.11.0
  CHANGELOG.md
  go.mod
  go.sum
  modules/apps/callbacks/go.mod
  modules/apps/callbacks/go.sum
Labels: priority
