Repository cosmos/ibc-go, pull requests merged in 2024-04, with the labels that each got.

#6055 feat: adding `ConsensusHost` interface for custom self client/consensus state validation
  CHANGELOG.md
  modules/core/02-client/abci.go
  modules/core/02-client/keeper/keeper.go
  modules/core/02-client/keeper/keeper_test.go
  modules/core/02-client/keeper/migrations.go
  modules/core/02-client/migrations/v7/genesis_test.go
  modules/core/02-client/proposal_handler.go
  modules/core/02-client/types/client.go
  modules/core/02-client/types/errors.go
  modules/core/02-client/types/genesis_test.go
  modules/core/03-connection/keeper/handshake_test.go
  modules/core/genesis.go
  modules/core/keeper/keeper.go
  modules/core/keeper/migrations.go
  modules/core/migrations/v7/genesis_test.go
  modules/light-clients/07-tendermint/consensus_host.go
  modules/light-clients/07-tendermint/consensus_host_test.go
  modules/light-clients/08-wasm/testing/simapp/app.go
  modules/light-clients/08-wasm/types/consensus_host.go
  modules/light-clients/08-wasm/types/consensus_host_test.go
  testing/mock/consensus_host.go
  testing/simapp/upgrades.go
  testing/simapp/upgrades/upgrades.go
Labels: priority

#6053 feat: add light client module for Celestia DA light client
  modules/core/02-client/types/msgs.go
  modules/core/02-client/types/msgs_test.go
  modules/light-clients/07-celestia/celestia.pb.go
  modules/light-clients/07-celestia/client_state.go
  modules/light-clients/07-celestia/light_client_module.go
  modules/light-clients/07-celestia/light_client_module_test.go
  modules/light-clients/07-celestia/module.go
  modules/light-clients/07-celestia/store.go
  modules/light-clients/07-celestia/testing/simapp/app.go
  modules/light-clients/07-celestia/update.go
  modules/light-clients/07-celestia/upgrade.go
  proto/ibc/lightclients/celestia/v1/celestia.proto
Labels: priority

#6081 refactor: standardise sub keeper usage in core ibc
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  modules/apps/29-fee/keeper/keeper_test.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/keeper/keeper_test.go
  modules/core/02-client/genesis.go
  modules/core/02-client/keeper/client.go
  modules/core/02-client/keeper/encoding.go
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/keeper/keeper.go
  modules/core/02-client/migrations/v7/genesis_test.go
  modules/core/02-client/types/genesis_test.go
  modules/core/03-connection/genesis.go
  modules/core/03-connection/keeper/grpc_query.go
  modules/core/03-connection/keeper/handshake.go
  modules/core/03-connection/keeper/keeper.go
  modules/core/03-connection/keeper/migrations.go
  modules/core/03-connection/keeper/verify.go
  modules/core/04-channel/genesis.go
  modules/core/04-channel/keeper/export_test.go
  modules/core/04-channel/keeper/grpc_query.go
  modules/core/04-channel/keeper/handshake.go
  modules/core/04-channel/keeper/keeper.go
  modules/core/04-channel/keeper/migrations.go
  modules/core/04-channel/keeper/packet.go
  modules/core/04-channel/keeper/timeout.go
  modules/core/04-channel/keeper/upgrade.go
  modules/core/05-port/keeper/keeper.go
  modules/core/genesis.go
  modules/core/keeper/grpc_query.go
  modules/core/keeper/keeper.go
  modules/core/keeper/msg_server.go
  modules/core/keeper/msg_server_test.go
  modules/core/migrations/v7/genesis_test.go
Labels: priority

#6074 test: move 07-tendermint client state testing to use light client module entry points
  modules/light-clients/07-tendermint/client_state.go
  modules/light-clients/07-tendermint/client_state_test.go
  modules/light-clients/07-tendermint/errors.go
  modules/light-clients/07-tendermint/light_client_module.go
  modules/light-clients/07-tendermint/light_client_module_test.go
  modules/light-clients/07-tendermint/tendermint_test.go
Labels: priority

#6137 fix: remove check that client type returned by client state and consensus state match
  modules/core/02-client/types/genesis.go
  modules/core/02-client/types/genesis_test.go
  modules/core/02-client/types/msgs.go
  modules/core/02-client/types/msgs_test.go
Labels: priority

#5979 imp(e2e): added generic grpc querier
  e2e/tests/core/02-client/client_test.go
  e2e/tests/core/03-connection/connection_test.go
  e2e/tests/interchain_accounts/base_test.go
  e2e/tests/interchain_accounts/gov_test.go
  e2e/tests/interchain_accounts/groups_test.go
  e2e/tests/interchain_accounts/incentivized_test.go
  e2e/tests/interchain_accounts/localhost_test.go
  e2e/tests/interchain_accounts/params_test.go
  e2e/tests/interchain_accounts/query_test.go
  e2e/tests/interchain_accounts/upgrades_test.go
  e2e/tests/transfer/authz_test.go
  e2e/tests/transfer/base_test.go
  e2e/tests/transfer/incentivized_test.go
  e2e/tests/transfer/localhost_test.go
  e2e/tests/transfer/upgrades_test.go
  e2e/tests/upgrades/genesis_test.go
  e2e/tests/upgrades/upgrade_test.go
  e2e/tests/wasm/grandpa_test.go
  e2e/tests/wasm/upgrade_test.go
  e2e/testsuite/grpc_query.go
  e2e/testsuite/query/grpc_query.go
  e2e/testsuite/query/queries.go
  e2e/testsuite/testsuite.go
  e2e/testsuite/tx.go
Labels: e2e

#5550 test: add panic cases in tests for `UpgradeOpen`
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
Labels: automerge, channel-upgradability

#6167 fix: avoid panic when migrate param for newly added host
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/keeper/migrations.go
  modules/apps/27-interchain-accounts/controller/keeper/migrations_test.go
  modules/apps/27-interchain-accounts/host/keeper/migrations.go
  modules/apps/27-interchain-accounts/host/keeper/migrations_test.go
  modules/apps/27-interchain-accounts/types/expected_keepers.go
Labels: backport-to-v8.3.x

#6126 chore: implement required `FungibleTokenPacketData` v3 interface methods
  modules/apps/transfer/internal/denom/denom.go
  modules/apps/transfer/types/trace.go
  modules/apps/transfer/types/v3/packet.go
  modules/apps/transfer/types/v3/packet_test.go
  modules/apps/transfer/types/v3/token.go
  modules/apps/transfer/types/v3/token_test.go
Labels: 20-transfer, priority

#6231 feat(08-wasm): expose migrate entry point for 08-wasm
  docs/docs/03-light-clients/04-wasm/08-client.md
  modules/light-clients/08-wasm/CHANGELOG.md
  modules/light-clients/08-wasm/client/cli/cli.go
  modules/light-clients/08-wasm/client/cli/tx.go
Labels: backport-wasm-v0.2.x+ibc-go-v8.3.x-wasmvm-v2.0.x

#6188 feat(depinject): support 08 wasm
  api/ibc/lightclients/wasm/module/v1/module.pulsar.go
  modules/light-clients/08-wasm/depinject.go
  modules/light-clients/08-wasm/go.mod
  modules/light-clients/08-wasm/module.go
  modules/light-clients/08-wasm/testing/simapp/app.go
  proto/ibc/lightclients/wasm/module/v1/module.proto
Labels: priority
