Repository cosmos/ibc-go, pull requests merged in 2024-10, with the labels that each got.

#7358 Add fallback function to grab counterparty for non-eureka channels
  modules/core/04-channel/keeper/keeper.go
  modules/core/04-channel/keeper/keeper_test.go
  modules/core/packet-server/keeper/relay.go
  modules/core/packet-server/types/expected_keepers.go
Labels: automerge

#7397 fix: avoid invalid identifier error when validate genesis
  CHANGELOG.md
  modules/core/03-connection/types/genesis.go
  modules/core/03-connection/types/genesis_test.go
Labels: backport-to-v9.0.x, backport-to-v8.5.x

#7413 Implement MsgSendPacket RPC handler and tests
  modules/core/04-channel/v2/keeper/keeper.go
  modules/core/04-channel/v2/keeper/msg_server.go
  modules/core/04-channel/v2/keeper/msg_server_test.go
  modules/core/04-channel/v2/keeper/packet.go
  modules/core/04-channel/v2/types/msgs.go
  modules/core/keeper/keeper.go
  simapp/app.go
  testing/mock/v2/mock.go
  testing/simapp/app.go
Labels: priority
