Repository cosmos/ibc-go, pull requests merged in 2024-05, with the labels that each got.

#6175 chore: implement version checking for channel handshake application callbacks
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/types/keys.go
Labels: 20-transfer, priority

#6253 imp(apps): allow one sided fee middleware handshakes to complete
  CHANGELOG.md
  modules/apps/27-interchain-accounts/host/keeper/handshake.go
  modules/apps/27-interchain-accounts/host/keeper/handshake_test.go
  modules/apps/29-fee/fee_test.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ica_test.go
  modules/apps/29-fee/transfer_test.go
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/ibc_module_test.go
  testing/endpoint.go
Labels: 20-transfer, 29-fee, 27-interchain-accounts, priority, backport-to-v8.3.x, backport-to-v7.5.x

#6251 feat(release/v8.3.x): use unordered ordering by default for new ica channels
  modules/apps/27-interchain-accounts/controller/client/cli/tx.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
  modules/apps/27-interchain-accounts/controller/migrations/v6/migrations_test.go
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  modules/apps/29-fee/ica_test.go
  modules/apps/callbacks/callbacks_test.go
Labels: priority

#6256 imp: check length of slices of messages
  CHANGELOG.md
  modules/apps/27-interchain-accounts/host/types/params.go
  modules/apps/27-interchain-accounts/host/types/params_test.go
  modules/core/02-client/types/params.go
  modules/core/02-client/types/params_test.go
  modules/core/03-connection/types/msgs.go
  modules/core/03-connection/types/msgs_test.go
  modules/core/03-connection/types/version.go
Labels: priority, backport-to-v8.3.x, backport-to-v7.5.x

#6267 feat(release/v7.5.x): use unordered ordering by default for new ica channels
  modules/apps/27-interchain-accounts/controller/client/cli/tx.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/controller/keeper/account.go
  modules/apps/27-interchain-accounts/controller/keeper/keeper_test.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server.go
  modules/apps/27-interchain-accounts/controller/keeper/msg_server_test.go
  modules/apps/27-interchain-accounts/controller/migrations/v6/migrations_test.go
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/27-interchain-accounts/host/keeper/keeper_test.go
  modules/apps/29-fee/ica_test.go
  modules/apps/callbacks/callbacks_test.go
  modules/apps/callbacks/go.mod
  modules/apps/callbacks/go.sum
  modules/apps/callbacks/testing/simapp/app.go
Labels: priority

#6189 ics20-v2: backwards compatibility for transfer rpc and packet callbacks
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/internal/convert/convert.go
  modules/apps/transfer/internal/convert/convert_test.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/events.go
  modules/apps/transfer/types/v3/token.go
  testing/solomachine.go
Labels: 20-transfer

#6268 imp: allow memo strings instead of keys for transfer authorizations
  CHANGELOG.md
  docs/docs/02-apps/01-transfer/08-authorizations.md
  modules/apps/transfer/types/authz.pb.go
  modules/apps/transfer/types/keys.go
  modules/apps/transfer/types/transfer_authorization.go
  modules/apps/transfer/types/transfer_authorization_test.go
  proto/ibc/applications/transfer/v1/authz.proto
Labels: priority, backport-to-v8.3.x, backport-to-v7.5.x

#6276 fix: noop on UpdateState for invalid misbehaviour
  CHANGELOG.md
  modules/light-clients/07-tendermint/update.go
  modules/light-clients/07-tendermint/update_test.go
Labels: priority, backport-to-v8.3.x, backport-to-v7.5.x

#6294 docs: bump docusaurus to v3.3 and improve kapa ai
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: docs

#6300 deps: bump cosmos sdk to v0.50.6 and comet bft to v0.38.7
  CHANGELOG.md
  go.mod
  go.sum
  modules/apps/callbacks/go.mod
  modules/apps/callbacks/go.sum
  modules/capability/go.mod
  modules/capability/go.sum
Labels: type: dependencies

#6279 imp: add updateClientCheckTx to redunant relayer ante decorator
  modules/core/ante/ante.go
  modules/core/ante/ante_test.go
Labels: priority, backport-to-v8.3.x, backport-to-v7.5.x

#6312 docs: fixed compile error
  .github/workflows/check-docs.yml
  docs/docusaurus.config.js
Labels: docs, github_actions

#6278 perf: exclude pruning from tendermint update client in ante handler execution
  CHANGELOG.md
  modules/light-clients/07-tendermint/update.go
  modules/light-clients/07-tendermint/update_test.go
Labels: priority, backport-to-v8.3.x

#6302 perf: minimize necessary execution on recvpacket checktx
  CHANGELOG.md
  modules/core/ante/ante.go
  modules/core/ante/ante_test.go
Labels: priority, backport-to-v7.4.x, backport-to-v8.3.x, backport-to-v7.5.x

#6338 docs: fix kapa.ai analytics config
  docs/docusaurus.config.js
Labels: docs

#6280 perf: minimize logic on rechecktx for recvpacket
  CHANGELOG.md
  modules/core/04-channel/keeper/ante.go
  modules/core/04-channel/keeper/ante_test.go
  modules/core/04-channel/keeper/packet.go
  modules/core/ante/ante.go
  modules/core/ante/ante_test.go
Labels: priority, backport-to-v7.4.x, backport-to-v8.3.x, backport-to-v7.5.x

#6306 refactor(v7.4.x): performance improvements for update client in ante
  CHANGELOG.md
  modules/core/ante/ante.go
  modules/core/ante/ante_test.go
Labels: priority

#6345 Adding additional comments and changing version variable names
  e2e/tests/transfer/localhost_test.go
  e2e/tests/transfer/upgrades_test.go
  e2e/testsuite/testsuite.go
  modules/apps/29-fee/keeper/events_test.go
  modules/apps/29-fee/transfer_test.go
  modules/apps/callbacks/callbacks_test.go
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/types/keys.go
  testing/path.go
  testing/solomachine.go
Labels: priority

#6339 docs: added a version matrix to callbacks and 08-wasm
  docs/docs/03-light-clients/04-wasm/03-integration.md
  docs/docs/04-middleware/02-callbacks/02-integration.md
  docs/versioned_docs/version-v7.5.x/03-light-clients/04-wasm/03-integration.md
  docs/versioned_docs/version-v7.5.x/04-middleware/02-callbacks/02-integration.md
  docs/versioned_docs/version-v8.3.x/03-light-clients/04-wasm/03-integration.md
  docs/versioned_docs/version-v8.3.x/04-middleware/02-callbacks/02-integration.md
  modules/apps/callbacks/README.md
  modules/light-clients/08-wasm/README.md
Labels: docs

#6135 chore: follow up for testing rest of methods on 07-tendermint light client module
  modules/core/02-client/keeper/client_test.go
  modules/core/02-client/keeper/keeper_test.go
  modules/light-clients/07-tendermint/light_client_module_test.go
  modules/light-clients/07-tendermint/misbehaviour_handle_test.go
  modules/light-clients/07-tendermint/update_test.go
  modules/light-clients/07-tendermint/upgrade_test.go
Labels: priority

#6348 imp: change ics20 events to emit token set
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/internal/convert/convert.go
  modules/apps/transfer/internal/convert/convert_test.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/events.go
  modules/apps/transfer/types/msgs.go
  modules/apps/transfer/types/packet.go
  modules/apps/transfer/types/packet.pb.go
  modules/apps/transfer/types/packet_test.go
  modules/apps/transfer/types/token.go
  modules/apps/transfer/types/token_test.go
  proto/ibc/applications/transfer/v2/packet.proto
Labels: priority

#6089 test: added packet data forwards compatibility test
  modules/apps/transfer/keeper/relay_test.go
Labels: testing, priority

#6354 Refactor packet data unmarshalling to use specific version
  modules/apps/callbacks/callbacks_test.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/callbacks/types/callbacks_test.go
  modules/apps/callbacks/types/export_test.go
  modules/apps/callbacks/types/types_test.go
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/ibc_module_test.go
Labels: priority

#6359 Sync Feature Branch With Main
  .github/workflows/proto-registry.yml
  docs/docs/03-light-clients/01-developer-guide/01-overview.md
  docs/docs/03-light-clients/01-developer-guide/02-light-client-module.md
  docs/docs/03-light-clients/01-developer-guide/05-updates-and-misbehaviour.md
  docs/docs/03-light-clients/01-developer-guide/06-upgrades.md
  docs/docs/03-light-clients/01-developer-guide/07-proofs.md
  docs/docs/03-light-clients/01-developer-guide/08-proposals.md
  docs/docs/03-light-clients/01-developer-guide/09-setup.md
  docs/docs/03-light-clients/02-localhost/03-client-state.md
  docs/docs/03-light-clients/02-localhost/05-state-verification.md
  docs/docs/03-light-clients/04-wasm/02-concepts.md
  docs/docs/03-light-clients/04-wasm/03-integration.md
  docs/docs/03-light-clients/04-wasm/04-messages.md
  docs/versioned_docs/version-v7.5.x/03-light-clients/01-developer-guide/06-proofs.md
  docs/versioned_docs/version-v8.3.x/03-light-clients/01-developer-guide/01-overview.md
  docs/versioned_docs/version-v8.3.x/03-light-clients/01-developer-guide/06-proofs.md
  modules/apps/callbacks/testing/simapp/app.go
  modules/apps/transfer/keeper/relay_test.go
  modules/light-clients/08-wasm/testing/simapp/app.go
  testing/README.md
  testing/simapp/app.go
Labels: priority

#6360 imp: self review comments for ics20-v2
  CHANGELOG.md
  docs/docs/05-migrations/13-v8-to-v9.md
  e2e/testsuite/testsuite.go
  modules/apps/transfer/types/keys.go
  modules/apps/transfer/types/token_test.go
Labels: priority

#6380 deps: bump go 1.22
  .github/workflows/callbacks.yml
  .github/workflows/capability.yml
  .github/workflows/e2e-compatibility-workflow-call.yaml
  .github/workflows/e2e-fork.yml
  .github/workflows/e2e-test-workflow-call.yml
  .github/workflows/e2e-wasm.yaml
  .github/workflows/e2e.yaml
  .github/workflows/e2emodule.yml
  .github/workflows/golangci-feature.yml
  .github/workflows/golangci.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/wasm-client.yml
  CHANGELOG.md
  Dockerfile
  e2e/go.mod
  go.mod
  go.work.example
  modules/apps/callbacks/Dockerfile
  modules/apps/callbacks/go.mod
  modules/capability/go.mod
  modules/light-clients/08-wasm/Dockerfile
  modules/light-clients/08-wasm/go.mod
Labels: priority

#6409 refactor: add Denom type and embed into Token
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/internal/convert/convert.go
  modules/apps/transfer/internal/convert/convert_test.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/packet.pb.go
  modules/apps/transfer/types/packet_test.go
  modules/apps/transfer/types/token.go
  modules/apps/transfer/types/token.pb.go
  modules/apps/transfer/types/token_test.go
  proto/ibc/applications/transfer/v2/packet.proto
  proto/ibc/applications/transfer/v2/token.proto
Labels: priority

#6411 refactor: remove encoding funcs for DenomTrace
  modules/apps/transfer/keeper/encoding.go
  modules/apps/transfer/keeper/grpc_query.go
  modules/apps/transfer/keeper/keeper.go
  modules/apps/transfer/module.go
  modules/apps/transfer/simulation/decoder.go
  modules/apps/transfer/simulation/decoder_test.go
Labels: priority

#6403 Add additional v2 test cases to callbacks
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/callbacks/types/callbacks_test.go
Labels: priority

#6423 refactor: rename GetFullPath to FullPath, add tests, rework impl
  modules/apps/transfer/keeper/grpc_query_test.go
  modules/apps/transfer/keeper/keeper.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/types/denom.go
  modules/apps/transfer/types/denom_test.go
Labels: priority

#6396 docs: fixed and improved "View Source" on docusaurus code blocks
  docs/src/theme/CodeBlock/index.js
  docs/tutorials/01-fee/03-scaffold-chain.md
  docs/tutorials/01-fee/05-scaffold-react.md
Labels: docs

#6426 refactor: add constructTokenFromCoin func + move IsSource funcs to Denom type
  modules/apps/transfer/keeper/export_test.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/types/coin.go
  modules/apps/transfer/types/denom.go
Labels: priority

#6427 refactor: remove GetTransferCoin
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/coin.go
Labels: priority

#6424 refactor: condense v1 denom parsing to single function
  modules/apps/transfer/internal/convert/convert.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/trace.go
Labels: priority

#6431 Add more unit tests for ExtractDenomFromFullPath
  modules/apps/transfer/types/trace_test.go
Labels: priority

#6432 refactor: use typed Trace
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/internal/convert/convert_test.go
  modules/apps/transfer/keeper/genesis_test.go
  modules/apps/transfer/keeper/grpc_query_test.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/transfer_test.go
  modules/apps/transfer/types/denom.go
  modules/apps/transfer/types/denom_test.go
  modules/apps/transfer/types/packet.go
  modules/apps/transfer/types/packet_test.go
  modules/apps/transfer/types/query.pb.go
  modules/apps/transfer/types/token.go
  modules/apps/transfer/types/token.pb.go
  modules/apps/transfer/types/token_test.go
  modules/apps/transfer/types/trace.go
  modules/apps/transfer/types/trace_test.go
  proto/ibc/applications/transfer/v1/query.proto
  proto/ibc/applications/transfer/v2/token.proto
Labels: priority
