Repository cosmos/ibc-go, pull requests merged in 2024-07, with the labels that each got.

#6694 Add support to run full test suite in run-e2e.sh
  e2e/Makefile
  e2e/scripts/run-e2e.sh
  e2e/testsuite/testsuite.go
Labels: e2e, priority

#6716 feat: add a method to check if the scope module already exists in the capability keeper
  modules/capability/CHANGELOG.md
  modules/capability/keeper/keeper.go
  modules/capability/keeper/keeper_test.go
Labels: backport-capability-to-v1.0.x

#6393 docs: migration docs for transfer multidenom
  docs/docs/05-migrations/13-v8-to-v9.md
Labels: priority

#6708 docs: update v9 migration doc for merkle path v2
  docs/docs/05-migrations/13-v8-to-v9.md
Labels: priority

#6644 refactor!: add v2 `MerklePath` with bytes in favour of strings
  CHANGELOG.md
  modules/core/02-client/keeper/grpc_query_test.go
  modules/core/02-client/types/query.pb.go
  modules/core/03-connection/keeper/verify.go
  modules/core/23-commitment/types/commitment.pb.go
  modules/core/23-commitment/types/merkle.go
  modules/core/23-commitment/types/merkle_test.go
  modules/core/23-commitment/types/utils_test.go
  modules/core/23-commitment/types/v2/commitment.pb.go
  modules/core/23-commitment/types/v2/merkle.go
  modules/light-clients/06-solomachine/client_state.go
  modules/light-clients/06-solomachine/light_client_module_test.go
  modules/light-clients/07-tendermint/client_state.go
  modules/light-clients/07-tendermint/light_client_module_test.go
  modules/light-clients/07-tendermint/upgrade.go
  modules/light-clients/08-wasm/CHANGELOG.md
  modules/light-clients/08-wasm/keeper/querier_test.go
  modules/light-clients/08-wasm/light_client_module.go
  modules/light-clients/08-wasm/light_client_module_test.go
  modules/light-clients/08-wasm/types/contract_api.go
  modules/light-clients/09-localhost/client_state.go
  modules/light-clients/09-localhost/light_client_module_test.go
  proto/ibc/core/client/v1/query.proto
  proto/ibc/core/commitment/v1/commitment.proto
  proto/ibc/core/commitment/v2/commitment.proto
  testing/solomachine.go
Labels: priority

#6683 feat: make 09-localhost stateless
  docs/docs/03-light-clients/02-localhost/01-overview.md
  docs/docs/03-light-clients/02-localhost/03-client-state.md
  docs/docs/03-light-clients/02-localhost/05-state-verification.md
  docs/docs/05-migrations/13-v8-to-v9.md
  e2e/tests/core/02-client/client_test.go
  e2e/tests/transfer/localhost_test.go
  e2e/testsuite/codec.go
  modules/core/02-client/abci.go
  modules/core/02-client/genesis.go
  modules/core/02-client/keeper/client_test.go
  modules/core/02-client/keeper/grpc_query_test.go
  modules/core/02-client/keeper/keeper.go
  modules/core/02-client/keeper/keeper_test.go
  modules/core/02-client/keeper/migrations.go
  modules/core/02-client/keeper/migrations_test.go
  modules/core/02-client/migrations/v7/expected_keepers.go
  modules/core/02-client/migrations/v7/localhost.go
  modules/core/02-client/migrations/v7/localhost_test.go
  modules/core/module.go
  modules/core/types/codec.go
  modules/light-clients/08-wasm/keeper/contract_keeper_test.go
  modules/light-clients/08-wasm/keeper/msg_server_test.go
  modules/light-clients/09-localhost/client_state.go
  modules/light-clients/09-localhost/client_state_test.go
  modules/light-clients/09-localhost/codec.go
  modules/light-clients/09-localhost/codec_test.go
  modules/light-clients/09-localhost/keys.go
  modules/light-clients/09-localhost/light_client_module.go
  modules/light-clients/09-localhost/light_client_module_test.go
  modules/light-clients/09-localhost/localhost.pb.go
  modules/light-clients/09-localhost/localhost_test.go
  modules/light-clients/09-localhost/store.go
  proto/ibc/lightclients/localhost/v2/localhost.proto
Labels: priority

#6712 chore: pull out get light client module to helper methods
  modules/core/02-client/keeper/client.go
  modules/core/02-client/keeper/keeper.go
  modules/light-clients/09-localhost/client_state.go
Labels: priority

#6749 imp: modify ica controller `NewIBCMiddleware` to default to nil auth module
  CHANGELOG.md
  docs/docs/02-apps/02-interchain-accounts/04-integration.md
  docs/docs/02-apps/02-interchain-accounts/10-legacy/02-integration.md
  docs/docs/05-migrations/13-v8-to-v9.md
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/29-fee/fee_test.go
  modules/apps/callbacks/testing/simapp/app.go
  modules/light-clients/08-wasm/testing/simapp/app.go
  testing/simapp/app.go
Labels: priority

#6747 deps: bump capability to v1.0.1
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
  modules/apps/callbacks/go.mod
  modules/apps/callbacks/go.sum
  modules/light-clients/08-wasm/go.mod
  modules/light-clients/08-wasm/go.sum
Labels: dependencies

#5746 docs: channel upgrades tutorial
  docs/tutorials/02-channel-upgrades/01-intro.md
  docs/tutorials/02-channel-upgrades/02-setup-env.md
  docs/tutorials/02-channel-upgrades/03-run-chains.md
  docs/tutorials/02-channel-upgrades/04-open-transfer-channel.md
  docs/tutorials/02-channel-upgrades/05-upgrade-channel.md
  docs/tutorials/02-channel-upgrades/06-incentivize-packet.md
  docs/tutorials/02-channel-upgrades/_category_.json
Labels: docs

#6758 (test) Test that tokens are successfully forwarded from A to C through B
  e2e/tests/transfer/forwarding_test.go
  e2e/testsuite/testsuite.go
Labels: priority

#6721 Enable Parallel Transfer Test Suite
  .github/workflows/e2e-test-workflow-call.yml
  .github/workflows/e2e.yaml
  e2e/Makefile
  e2e/scripts/run-e2e.sh
  e2e/tests/core/02-client/client_test.go
  e2e/tests/core/03-connection/connection_test.go
  e2e/tests/interchain_accounts/base_test.go
  e2e/tests/interchain_accounts/gov_test.go
  e2e/tests/interchain_accounts/groups_test.go
  e2e/tests/interchain_accounts/incentivized_test.go
  e2e/tests/interchain_accounts/localhost_test.go
  e2e/tests/interchain_accounts/params_test.go
  e2e/tests/interchain_accounts/query_test.go
  e2e/tests/interchain_accounts/upgrades_test.go
  e2e/tests/transfer/authz_test.go
  e2e/tests/transfer/base_test.go
  e2e/tests/transfer/forwarding_test.go
  e2e/tests/transfer/incentivized_test.go
  e2e/tests/transfer/localhost_test.go
  e2e/tests/transfer/send_enabled_test.go
  e2e/tests/transfer/send_receive_test.go
  e2e/tests/transfer/upgradesv1_test.go
  e2e/tests/transfer/upgradesv2_test.go
  e2e/tests/upgrades/genesis_test.go
  e2e/tests/upgrades/upgrade_test.go
  e2e/tests/wasm/grandpa_test.go
  e2e/testsuite/testsuite.go
Labels: e2e, priority

#6760 imp: remove `Route` method in favour of `Verify(Non)Membership` on client keeper
  modules/core/02-client/keeper/client.go
  modules/core/02-client/keeper/keeper.go
  modules/core/03-connection/keeper/verify.go
  modules/core/03-connection/types/expected_keepers.go
Labels: priority

#6763 refactor(core)!: move telemetry into internal folder
  CHANGELOG.md
  modules/apps/transfer/internal/telemetry/telemetry.go
  modules/core/02-client/keeper/client.go
  modules/core/02-client/types/metrics.go
  modules/core/internal/telemetry/client.go
  modules/core/internal/telemetry/packet.go
  modules/core/keeper/msg_server.go
  modules/core/metrics/metrics.go
Labels: priority

#6766 Enabling additional tests to run in parallel
  .github/workflows/e2e-test-workflow-call.yml
  .github/workflows/e2e.yaml
  e2e/tests/core/03-connection/connection_test.go
  e2e/tests/interchain_accounts/incentivized_test.go
  e2e/tests/transfer/authz_test.go
  e2e/tests/transfer/forwarding_test.go
  e2e/tests/transfer/incentivized_test.go
  e2e/tests/transfer/upgradesv1_test.go
  e2e/tests/transfer/upgradesv2_test.go
  e2e/tests/upgrades/upgrade_test.go
  e2e/testsuite/testsuite.go
  e2e/testsuite/tx.go
Labels: priority

#6791 test: e2e upgrade tests for v8 -> v9
  .github/workflows/e2e-upgrade.yaml
  e2e/tests/upgrades/genesis_test.go
  e2e/tests/upgrades/upgrade_test.go
  e2e/testsuite/query/grpc_query.go
  e2e/testsuite/query/queries.go
  e2e/testsuite/testconfig.go
  modules/apps/transfer/module.go
  simapp/upgrades.go
  simapp/upgrades/upgrades.go
Labels: priority

#6794 refactor: use unexported types for core query servers
  CHANGELOG.md
  docs/docs/05-migrations/13-v8-to-v9.md
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/keeper/grpc_query_test.go
  modules/core/02-client/module.go
  modules/core/03-connection/keeper/grpc_query.go
  modules/core/03-connection/keeper/grpc_query_test.go
  modules/core/03-connection/module.go
  modules/core/04-channel/keeper/grpc_query.go
  modules/core/04-channel/keeper/grpc_query_test.go
  modules/core/04-channel/module.go
  modules/core/keeper/grpc_query.go
  modules/core/keeper/keeper.go
  modules/core/module.go
  modules/core/types/query.go
  testing/chain.go
Labels: priority

#6806 test: add v8 to v9 e2e upgrade tests with channel upgrade
  .github/workflows/e2e-upgrade.yaml
  e2e/tests/upgrades/upgrade_test.go
Labels: priority

#6837 refactor: simplify 02-client router funcs
  modules/core/02-client/keeper/client.go
  modules/core/02-client/keeper/client_test.go
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/keeper/grpc_query_test.go
  modules/core/02-client/keeper/keeper.go
  modules/core/02-client/types/keys.go
  modules/core/02-client/types/router.go
  modules/core/02-client/types/router_test.go
  modules/core/ante/ante.go
  modules/core/keeper/msg_server_test.go
  modules/light-clients/06-solomachine/light_client_module_test.go
  modules/light-clients/07-tendermint/light_client_module_test.go
  modules/light-clients/07-tendermint/misbehaviour_handle_test.go
  modules/light-clients/07-tendermint/update_test.go
  modules/light-clients/08-wasm/light_client_module_test.go
  modules/light-clients/09-localhost/light_client_module_test.go
Labels: priority

#6805 (test) Add tests for callback execution when forwarding a packet
  modules/apps/callbacks/forwarding_test.go
Labels: priority, backport-to-v9.0.x

#6885 (chore) update imports to v9
  modules/apps/callbacks/forwarding_test.go
Labels: priority

#6853 imp(02-client,03-connection)!: remove `ValidateSelfClient`
  modules/core/02-client/keeper/keeper.go
  modules/core/02-client/types/client.go
  modules/core/03-connection/keeper/handshake.go
  modules/core/03-connection/keeper/handshake_test.go
  modules/core/03-connection/types/expected_keepers.go
  modules/light-clients/07-tendermint/consensus_host.go
  modules/light-clients/07-tendermint/consensus_host_test.go
  modules/light-clients/08-wasm/types/consensus_host.go
  modules/light-clients/08-wasm/types/consensus_host_test.go
  testing/mock/consensus_host.go
Labels: 03-connection, 02-client

#6876 (tests): e2e test for failed forwarding
  e2e/tests/transfer/forwarding_test.go
  e2e/testsuite/testsuite.go
Labels: priority

#6897 chore: make UnmarshalPacketData public
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/internal/packet.go
  modules/apps/transfer/internal/packet_test.go
  modules/apps/transfer/types/packet.go
  modules/apps/transfer/types/packet_test.go
Labels: priority, backport-to-v9.0.x

#6877 (feat) Add possibility to transfer entire balance.
  .github/compatibility-test-matrices/main/transfer-v2-multidenom-chain-a.json
  .github/compatibility-test-matrices/release-v9.0.x/transfer-v2-multidenom-chain-a.json
  .github/compatibility-test-matrices/unreleased/transfer-v2-multidenom.json
  CHANGELOG.md
  docs/docs/02-apps/01-transfer/04-messages.md
  docs/docs/02-apps/01-transfer/10-ICS20-v1/04-messages.md
  e2e/tests/transfer/base_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/token.go
  modules/apps/transfer/types/transfer_authorization.go
  testing/chain.go
Labels: priority, backport-to-v9.0.x, backport-to-v7.7.x, backport-to-v8.4.x

#6932 nit: rename arguments of `acknowledgeForwardedPacket` for clarity
  modules/apps/transfer/keeper/forwarding.go
Labels: backport-to-v9.0.x

#6934 chore(api!): Replace GetRouter with AddRoute in 02-client keeper.
  docs/docs/01-ibc/02-integration.md
  docs/docs/03-light-clients/04-wasm/03-integration.md
  modules/apps/callbacks/testing/simapp/app.go
  modules/core/02-client/keeper/keeper.go
  modules/light-clients/08-wasm/testing/simapp/app.go
  simapp/app.go
  testing/simapp/app.go
Labels: priority, backport-to-v9.0.x

#6933 (chore) disallow unknown fields29 fee ack
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
  modules/apps/29-fee/types/encoding.go
Labels: priority, backport-to-v9.0.x

#6935 fix(state!): check upgrade compatibility in channel upgrade confirm
  CHANGELOG.md
  modules/core/04-channel/keeper/upgrade.go
  modules/core/04-channel/keeper/upgrade_test.go
Labels: priority, backport-to-v9.0.x, backport-to-v8.4.x

#6923 api!: rename path to merkle path for contract api json msgs
  modules/light-clients/08-wasm/CHANGELOG.md
  modules/light-clients/08-wasm/go.mod
  modules/light-clients/08-wasm/types/contract_api.go
Labels: priority

#6924 api!: rename path to merkle path for contract api json msgs
  modules/light-clients/08-wasm/CHANGELOG.md
  modules/light-clients/08-wasm/go.mod
  modules/light-clients/08-wasm/types/contract_api.go
Labels: priority

#6640 imp: emit defaults when marshalling clienttypes.Height to json
  modules/core/02-client/types/client.pb.go
  proto/ibc/core/client/v1/client.proto
Labels: priority, backport-to-v9.0.x

#6902 feat: add channel version to core app callbacks
  modules/apps/27-interchain-accounts/controller/ibc_middleware.go
  modules/apps/27-interchain-accounts/controller/ibc_middleware_test.go
  modules/apps/27-interchain-accounts/host/ibc_module.go
  modules/apps/27-interchain-accounts/host/ibc_module_test.go
  modules/apps/29-fee/ibc_middleware.go
  modules/apps/29-fee/ibc_middleware_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/keeper/relay_forwarding_test.go
  modules/core/04-channel/keeper/packet.go
  modules/core/04-channel/keeper/packet_test.go
  modules/core/04-channel/keeper/timeout.go
  modules/core/04-channel/keeper/timeout_test.go
  modules/core/05-port/types/module.go
  modules/core/ante/ante.go
  modules/core/ante/ante_test.go
  modules/core/keeper/msg_server.go
  testing/mock/ibc_app.go
  testing/mock/ibc_module.go
  testing/mock/middleware.go
Labels: priority, backport-to-v9.0.x

#6907 test: add NewForwardErrorAcknowledgement to multihop forwarding test
  modules/apps/transfer/keeper/relay_forwarding_test.go
Labels: priority, backport-to-v9.0.x

#6927 docs: update migration docs for 08-wasm pre-releases
  docs/docs/03-light-clients/04-wasm/09-migrations.md
Labels: priority

#6965 release/v8.4.x: retract v8.2.x and v8.3.x
  go.mod
Labels: priority

#6919 refactor: use client module for status checks in 02-client handlers
  modules/core/02-client/keeper/client.go
Labels: priority, backport-to-v9.0.x

#6870 api!: delete v1 merkle path and register v2 merkle path against interface on cdc
  CHANGELOG.md
  docs/client/swagger-ui/swagger.yaml
  docs/docs/05-migrations/13-v8-to-v9.md
  modules/core/23-commitment/types/codec.go
  modules/core/23-commitment/types/codec_test.go
  modules/core/23-commitment/types/commitment.pb.go
  modules/core/23-commitment/types/merkle.go
  modules/light-clients/06-solomachine/misbehaviour_handle.go
  modules/light-clients/09-localhost/light_client_module.go
  proto/ibc/core/commitment/v1/commitment.proto
Labels: priority, backport-to-v9.0.x
