Repository cosmos/ibc-go, pull requests merged in 2024-02, with the labels that each got.

#5493 add IBCClientHeader func for endpoint and update tests
  docs/docs/05-migrations/13-v8-to-v9.md
  modules/core/02-client/keeper/client_test.go
  modules/core/02-client/keeper/events_test.go
  modules/core/ante/ante_test.go
  modules/light-clients/07-tendermint/update_test.go
  testing/chain.go
  testing/endpoint.go
Labels: testing

#5830 refactor!: remove ZeroCustomFields from ClientState interface
  docs/docs/03-light-clients/01-developer-guide/02-client-state.md
  docs/docs/03-light-clients/01-developer-guide/05-upgrades.md
  docs/docs/05-migrations/13-v8-to-v9.md
  e2e/tests/core/02-client/client_test.go
  modules/core/02-client/keeper/client_test.go
  modules/core/02-client/keeper/keeper.go
  modules/core/02-client/keeper/keeper_test.go
  modules/core/02-client/migrations/v7/solomachine.go
  modules/core/02-client/types/legacy_proposal.go
  modules/core/exported/client.go
  modules/core/keeper/msg_server_test.go
  modules/light-clients/06-solomachine/client_state.go
  modules/light-clients/07-tendermint/client_state.go
  modules/light-clients/07-tendermint/upgrade.go
  modules/light-clients/07-tendermint/upgrade_test.go
  modules/light-clients/08-wasm/types/client_state.go
  modules/light-clients/09-localhost/client_state.go
  modules/light-clients/09-localhost/client_state_test.go
Labels: priority

#5821 feat: add rpc `VerifyMembershipProof` - querier approach for conditional clients
  docs/client/swagger-ui/swagger.yaml
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/keeper/grpc_query_test.go
  modules/core/02-client/types/query.pb.go
  modules/core/02-client/types/query.pb.gw.go
  modules/core/keeper/grpc_query.go
  modules/light-clients/08-wasm/types/querier.go
  modules/light-clients/08-wasm/types/querier_test.go
  proto/ibc/core/client/v1/query.proto
Labels: priority, backport-to-v8.2.x

#5824 02-client routing: function in store provider to return client store
  modules/core/02-client/types/store.go
Labels: 02-client, priority

#5822 02-client routing: implement `RecoverClient` in light client modules
  modules/core/02-client/keeper/client.go
  modules/core/02-client/keeper/client_test.go
  modules/core/exported/client.go
  modules/light-clients/06-solomachine/light_client_module.go
  modules/light-clients/06-solomachine/light_client_module_test.go
  modules/light-clients/07-tendermint/light_client_module.go
  modules/light-clients/07-tendermint/light_client_module_test.go
  modules/light-clients/08-wasm/light_client_module.go
  modules/light-clients/08-wasm/light_client_module_test.go
  modules/light-clients/08-wasm/types/proposal_handle_test.go
  modules/light-clients/08-wasm/wasm_test.go
Labels: 02-client, priority

#5870 chore: add client status check to verify membership rpc
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/keeper/grpc_query_test.go
Labels: backport-to-v8.2.x

#5871 imp: deny selected client types from VerifyMembership rpc
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/keeper/grpc_query_test.go
Labels: backport-to-v8.2.x

#5878 fix(08-wasm/test): register mockVm querier callbacks against TimestampAtHeightMsg to avoid recursive loops
  modules/light-clients/08-wasm/types/querier_test.go
Labels: priority, backport-wasm-v0.2.x+ibc-go-v8.2.x-wasmvm-v2.0.x

#5868 backport conditional clients support to 08-wasm
  docs/client/swagger-ui/swagger.yaml
  modules/core/02-client/keeper/grpc_query.go
  modules/core/02-client/keeper/grpc_query_test.go
  modules/core/02-client/types/query.pb.go
  modules/core/02-client/types/query.pb.gw.go
  modules/core/keeper/grpc_query.go
  modules/light-clients/08-wasm/go.mod
  modules/light-clients/08-wasm/types/querier.go
  modules/light-clients/08-wasm/types/querier_test.go
  proto/ibc/core/client/v1/query.proto
Labels: priority
