Repository cosmos/ibc-go, pull requests merged in 2024-06, with the labels that each got.

#6463 chore: rename `refundPacketToken` to `refundPacketTokens`
  modules/apps/transfer/keeper/relay.go
Labels: priority

#6462 test: add coverage for both `token` and `tokens` set in `MsgTransfer`
  modules/apps/transfer/types/msgs_test.go
Labels: priority

#6484 Add additional tests and comments for Transfer Authz
  modules/apps/transfer/types/transfer_authorization.go
  modules/apps/transfer/types/transfer_authorization_test.go
Labels: priority

#6467 chore: rename `denomination_trace` event type to `denomination`
  docs/docs/02-apps/01-transfer/05-events.md
  modules/apps/transfer/internal/events/events.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/types/events.go
Labels: priority

#6515 e2e: set transfer version depending on the chains' version
  e2e/tests/core/02-client/client_test.go
  e2e/tests/core/03-connection/connection_test.go
  e2e/tests/transfer/authz_test.go
  e2e/tests/transfer/base_test.go
  e2e/tests/transfer/incentivized_test.go
  e2e/tests/transfer/localhost_test.go
  e2e/tests/transfer/upgrades_test.go
  e2e/tests/upgrades/genesis_test.go
  e2e/tests/upgrades/upgrade_test.go
  e2e/testsuite/testsuite.go
  e2e/testsuite/tx.go
  e2e/testvalues/values.go
Labels: priority

#6377 Update ica simulated proposals to check which modules are instantianted.
  CHANGELOG.md
  modules/apps/27-interchain-accounts/module.go
  modules/apps/27-interchain-accounts/simulation/proposals.go
  modules/apps/27-interchain-accounts/simulation/proposals_test.go
Labels: priority

#6570 docs: made v8 the landing version and bumped docusaurus to v3.4
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  package-lock.json
Labels: docs

#6545 test: add more multi-denom test cases
  modules/apps/29-fee/transfer_test.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/transfer/keeper/invariants_test.go
  modules/apps/transfer/transfer_test.go
Labels: priority

#6524 Update E2E infra to support more than 2 chains
  e2e/tests/transfer/forwarding_test.go
  e2e/tests/upgrades/genesis_test.go
  e2e/tests/wasm/grandpa_test.go
  e2e/testsuite/testconfig.go
  e2e/testsuite/testsuite.go
Labels: priority

#6571 feat(transfer): add forwarding info validation to token packet
  modules/apps/transfer/types/errors.go
  modules/apps/transfer/types/forwarding_info.go
  modules/apps/transfer/types/forwarding_info_test.go
  modules/apps/transfer/types/packet.go
  modules/apps/transfer/types/packet_test.go
Labels: priority

#6575 Refactor packet forward functions
  modules/apps/transfer/keeper/forwarding.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/types/packet.go
Labels: priority

#6591 feat(transfer): validate forwarding memo in transfer authorization
  modules/apps/transfer/types/transfer_authorization.go
  modules/apps/transfer/types/transfer_authorization_test.go
Labels: priority

#6592 feat(transfer): move async decision and handling to the ibc module onrecv callback
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/internal/events/events.go
  modules/apps/transfer/keeper/mbt_relay_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_forwarding_test.go
  modules/apps/transfer/keeper/relay_test.go
Labels: priority

#6604 feat(transfer): use single byte ack for successful forward
  modules/apps/transfer/keeper/forwarding.go
  modules/apps/transfer/keeper/relay_forwarding_test.go
Labels: priority

#6290 tests(e2e): ics20 v2 multidenom
  .github/compatibility-test-matrices/main/transfer-v2-chain-a.json
  .github/compatibility-test-matrices/main/transfer-v2-channel-upgrade-chain-a.json
  .github/compatibility-test-matrices/unreleased/transfer-v2-channel-upgrade.json
  .github/compatibility-test-matrices/unreleased/transfer-v2.json
  e2e/tests/transfer/base_test.go
  e2e/tests/transfer/upgrades_test.go
Labels: priority

#6625 chore: backport #4992 to release/v7.6.x
  CHANGELOG.md
  modules/apps/27-interchain-accounts/controller/types/msgs.go
  modules/apps/27-interchain-accounts/controller/types/msgs_test.go
  modules/apps/27-interchain-accounts/types/account_test.go
  modules/apps/29-fee/types/msgs.go
  modules/apps/29-fee/types/msgs_test.go
  modules/apps/transfer/types/errors.go
  modules/apps/transfer/types/msgs.go
  modules/apps/transfer/types/msgs_test.go
  testing/utils.go
  testing/values.go
Labels: priority

#6629 Restructure E2Es to setup chain in SetupSuite and create channel in SetupTest #1
  e2e/dockerutil/dockerutil.go
  e2e/tests/core/02-client/client_test.go
  e2e/tests/core/03-connection/connection_test.go
  e2e/tests/interchain_accounts/base_test.go
  e2e/tests/interchain_accounts/gov_test.go
  e2e/tests/interchain_accounts/groups_test.go
  e2e/tests/interchain_accounts/incentivized_test.go
  e2e/tests/interchain_accounts/localhost_test.go
  e2e/tests/interchain_accounts/params_test.go
  e2e/tests/interchain_accounts/query_test.go
  e2e/tests/interchain_accounts/upgrades_test.go
  e2e/tests/transfer/authz_test.go
  e2e/tests/transfer/base_test.go
  e2e/tests/transfer/forwarding_test.go
  e2e/tests/transfer/incentivized_test.go
  e2e/tests/transfer/localhost_test.go
  e2e/tests/transfer/upgradesv1_test.go
  e2e/tests/transfer/upgradesv2_test.go
  e2e/tests/upgrades/genesis_test.go
  e2e/tests/upgrades/upgrade_test.go
  e2e/tests/wasm/grandpa_test.go
  e2e/tests/wasm/upgrade_test.go
  e2e/testsuite/diagnostics/diagnostics.go
  e2e/testsuite/testsuite.go
Labels: priority

#6633 refactor!: adapt merkle path to use repeated bytes in favour of strings
  CHANGELOG.md
  modules/core/23-commitment/types/commitment.pb.go
  modules/core/23-commitment/types/merkle.go
  modules/core/23-commitment/types/merkle_test.go
  proto/ibc/core/commitment/v1/commitment.proto
Labels: priority

#6595 feat(transfer): add ShouldBeForwarded convenience method to msg transfer
  modules/apps/transfer/types/msgs.go
  modules/apps/transfer/types/packet.go
  modules/apps/transfer/types/transfer_authorization.go
Labels: priority

#6641 disallow timeout height usage when forwarding packets
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/keeper/forwarding.go
  modules/apps/transfer/keeper/relay_forwarding_test.go
  modules/apps/transfer/types/msgs.go
  modules/apps/transfer/types/msgs_test.go
  testing/chain.go
  testing/values.go
Labels: priority

#6648 feat(transfer): use registered error code for error acks in token forwarding
  modules/apps/transfer/keeper/forwarding.go
  modules/apps/transfer/keeper/relay_forwarding_test.go
  modules/apps/transfer/types/errors.go
  testing/events.go
Labels: priority

#6438 docs: updates and improvements to integration section
  docs/docs/01-ibc/02-integration.md
Labels: priority

#6661 feat: allow authz granters to specify forwarding info for token transfer
  modules/apps/transfer/types/authz.pb.go
  modules/apps/transfer/types/transfer_authorization.go
  modules/apps/transfer/types/transfer_authorization_test.go
  proto/ibc/applications/transfer/v1/authz.proto
Labels: priority

#6621 feat: delete forwarded packet when it is not needed anymore
  modules/apps/transfer/keeper/forwarding.go
  modules/apps/transfer/keeper/keeper.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_forwarding_test.go
Labels: priority

#6659 test(transfer): forwarding acknowledgment errors in middle hop
  modules/apps/transfer/keeper/relay_forwarding_test.go
Labels: priority

#6622 test(transfer): last chain in forwarding packet is ICS20 v1
  e2e/tests/transfer/forwarding_test.go
  e2e/testsuite/testsuite.go
Labels: priority

#6660 Fix Wasm E2E Tests
  e2e/tests/wasm/grandpa_test.go
  e2e/testsuite/testsuite.go
  e2e/testsuite/tx.go
Labels: priority

#6656 feat(transfer): add unwinding ability
  modules/apps/transfer/keeper/export_test.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/types/authz.pb.go
  modules/apps/transfer/types/msgs.go
  modules/apps/transfer/types/msgs_test.go
  modules/apps/transfer/types/transfer_authorization.go
  modules/apps/transfer/types/transfer_authorization_test.go
  proto/ibc/applications/transfer/v1/authz.proto
Labels: priority

#6689 Wait for blocks after wallet creation
  e2e/testsuite/testsuite.go
Labels: e2e

#6697 (chore) replace reflect.DeepEqual with slices.Equal
  modules/apps/transfer/types/transfer_authorization.go
Labels: priority

#6691 chore: cleanup forwarding tests
  modules/apps/transfer/keeper/relay_forwarding_test.go
Labels: priority

#6695 chore: pull out hop validation and consolidate for transfer+packet
  modules/apps/transfer/types/forwarding.go
  modules/apps/transfer/types/forwarding_test.go
  modules/apps/transfer/types/msgs_test.go
  modules/apps/transfer/types/packet_test.go
Labels: priority

#6701 Remove unwind field in authz
  modules/apps/transfer/types/authz.pb.go
  modules/apps/transfer/types/transfer_authorization.go
  modules/apps/transfer/types/transfer_authorization_test.go
  proto/ibc/applications/transfer/v1/authz.proto
Labels: priority

#6685 Configure relayers to watch only channels associated with an individual test
  e2e/go.mod
  e2e/relayer/relayer.go
  e2e/tests/transfer/forwarding_test.go
  e2e/testsuite/testconfig.go
  e2e/testsuite/testsuite.go
Labels: priority

#6704 Add packet data validation back
  modules/apps/transfer/ibc_module.go
  modules/apps/transfer/keeper/export_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_test.go
Labels: priority

#6706 (chore) Refactor code around forwarding validation
  modules/apps/transfer/types/msgs.go
  modules/apps/transfer/types/msgs_test.go
Labels: priority

#6703 chore: pass only hops to sendTransfer and events
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/internal/events/events.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/types/events.go
Labels: priority

#6707 test: forwarding test that verifies forwarded memo
  modules/apps/transfer/keeper/relay_forwarding_test.go
  testing/events.go
  testing/events_test.go
Labels: priority

#6688 chore: use module account instead of custom forward address
  modules/apps/transfer/keeper/forwarding.go
  modules/apps/transfer/keeper/keeper.go
  modules/apps/transfer/keeper/keeper_test.go
  modules/apps/transfer/keeper/msg_server.go
  modules/apps/transfer/keeper/msg_server_test.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/keeper/relay_forwarding_test.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/types/keys.go
Labels: priority

#6671 docs: document limits in string fields
  docs/docs/02-apps/01-transfer/04-messages.md
  docs/docs/02-apps/02-interchain-accounts/05-messages.md
  docs/docs/04-middleware/01-ics29-fee/04-fee-distribution.md
  docs/versioned_docs/version-v7.6.x/02-apps/01-transfer/04-messages.md
  docs/versioned_docs/version-v7.6.x/02-apps/02-interchain-accounts/05-messages.md
  docs/versioned_docs/version-v7.6.x/04-middleware/01-ics29-fee/04-fee-distribution.md
  docs/versioned_docs/version-v8.3.x/02-apps/02-interchain-accounts/05-messages.md
  docs/versioned_docs/version-v8.3.x/04-middleware/01-ics29-fee/04-fee-distribution.md
Labels: priority

#6459 deps: update hermes to v1.10.0
  e2e/relayer/relayer.go
  e2e/tests/transfer/upgradesv2_test.go
  e2e/testsuite/testconfig.go
Labels: priority

#6713 (test) Add test for more than one forwarding hop
  modules/apps/transfer/keeper/keeper_test.go
  modules/apps/transfer/keeper/relay_forwarding_test.go
Labels: priority

#6705 imp: replace `Sender/ReceiverChainIsSource` with `HasPrefix`
  docs/docs/05-migrations/13-v8-to-v9.md
  modules/apps/transfer/keeper/forwarding.go
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/types/denom.go
  modules/apps/transfer/types/denom_test.go
Labels: priority
