Repository cosmos/ibc-go, pull requests merged in 2025-02, with the labels that each got.

#7911 deps: bump wasmvm to v2.2.2
  .github/workflows/test.yml
  e2e/go.mod
  e2e/go.sum
  modules/light-clients/08-wasm/go.mod
  modules/light-clients/08-wasm/go.sum
Labels: backport-to-v10.0.x

#7985 chore: update sonarqube gh action
  .github/workflows/callbacks.yml
  .github/workflows/test.yml
  .github/workflows/wasm-client.yml
Labels: backport-to-v8.5.x, backport-to-v7.8.x, backport-to-v10.0.x

#7976 test: fix ica compatibility tests
  .github/workflows/e2e-compatibility.yaml
  e2e/tests/interchain_accounts/params_test.go
  e2e/tests/interchain_accounts/query_test.go
  e2e/testsuite/query/grpc_query.go
  e2e/testsuite/testsuite.go
  e2e/testsuite/tx.go
Labels: backport-to-v10.0.x

#7993 Document ICS23 MerklePath
  modules/apps/27-interchain-accounts/controller/types/controller.pb.go
  modules/apps/27-interchain-accounts/controller/types/query.pb.go
  modules/apps/27-interchain-accounts/controller/types/tx.pb.go
  modules/apps/27-interchain-accounts/genesis/types/genesis.pb.go
  modules/apps/27-interchain-accounts/host/types/host.pb.go
  modules/apps/27-interchain-accounts/host/types/query.pb.go
  modules/apps/27-interchain-accounts/host/types/tx.pb.go
  modules/apps/27-interchain-accounts/types/account.pb.go
  modules/apps/27-interchain-accounts/types/metadata.pb.go
  modules/apps/27-interchain-accounts/types/packet.pb.go
  modules/apps/29-fee/types/ack.pb.go
  modules/apps/29-fee/types/fee.pb.go
  modules/apps/29-fee/types/genesis.pb.go
  modules/apps/29-fee/types/metadata.pb.go
  modules/apps/29-fee/types/query.pb.go
  modules/apps/29-fee/types/tx.pb.go
  modules/apps/transfer/internal/types/denomtrace.pb.go
  modules/apps/transfer/types/authz.pb.go
  modules/apps/transfer/types/genesis.pb.go
  modules/apps/transfer/types/packet.pb.go
  modules/apps/transfer/types/query.pb.go
  modules/apps/transfer/types/queryv2.pb.go
  modules/apps/transfer/types/token.pb.go
  modules/apps/transfer/types/transfer.pb.go
  modules/apps/transfer/types/tx.pb.go
  modules/core/02-client/migrations/v7/solomachine.pb.go
  modules/core/02-client/types/client.pb.go
  modules/core/02-client/types/genesis.pb.go
  modules/core/02-client/types/query.pb.go
  modules/core/02-client/types/tx.pb.go
  modules/core/02-client/v2/types/counterparty.pb.go
  modules/core/02-client/v2/types/genesis.pb.go
  modules/core/02-client/v2/types/query.pb.go
  modules/core/02-client/v2/types/tx.pb.go
  modules/core/03-connection/types/connection.pb.go
  modules/core/03-connection/types/genesis.pb.go
  modules/core/03-connection/types/query.pb.go
  modules/core/03-connection/types/tx.pb.go
  modules/core/04-channel/types/channel.pb.go
  modules/core/04-channel/types/genesis.pb.go
  modules/core/04-channel/types/query.pb.go
  modules/core/04-channel/types/tx.pb.go
  modules/core/04-channel/types/upgrade.pb.go
  modules/core/04-channel/v2/types/genesis.pb.go
  modules/core/04-channel/v2/types/packet.pb.go
  modules/core/04-channel/v2/types/query.pb.go
  modules/core/04-channel/v2/types/tx.pb.go
  modules/core/23-commitment/types/commitment.pb.go
  modules/core/23-commitment/types/v2/commitment.pb.go
  modules/core/23-commitment/types/v2/merkle.go
  modules/core/types/genesis.pb.go
  modules/light-clients/06-solomachine/solomachine.pb.go
  modules/light-clients/07-tendermint/tendermint.pb.go
  proto/ibc/applications/transfer/v1/authz.proto
  proto/ibc/applications/transfer/v2/genesis.proto
  proto/ibc/applications/transfer/v2/packet.proto
  proto/ibc/core/commitment/v2/commitment.proto
Labels: backport-to-v10.0.x

#7997 feat: add cli commands for client v2 counterparty
  modules/core/02-client/client/cli/cli.go
  modules/core/02-client/client/cli/query.go
  modules/core/02-client/client/cli/tx.go
  modules/light-clients/08-wasm/internal/types/store_test.go
  modules/light-clients/08-wasm/keeper/keeper_test.go
  modules/light-clients/08-wasm/testing/simapp/app.go
  modules/light-clients/08-wasm/testing/simapp/simd/cmd/root.go
  modules/light-clients/08-wasm/testing/simapp/test_helpers.go
  modules/light-clients/08-wasm/types/types_test.go
  modules/light-clients/08-wasm/wasm_test.go
Labels: backport-to-v10.0.x

#8005 chore: add deprecated functions for backwards compat
  modules/apps/transfer/keeper/relay.go
  modules/apps/transfer/types/denom.go
  modules/apps/transfer/types/deprecated.go
Labels: backport-to-v10.0.x

#8006 chore: use ibc v2 name consistently
  RELEASES.md
  e2e/README.md
  modules/apps/callbacks/v2/v2_test.go
  modules/apps/transfer/v2/ibc_module.go
  modules/apps/transfer/v2/ibc_module_test.go
  modules/core/04-channel/v2/types/events.go
  modules/core/keeper/msg_server.go
  modules/light-clients/08-wasm/blsverifier/handler.go
  testing/path.go
Labels: backport-to-v10.0.x

#8014 callbacks: Error on RecvPacket callback execution
  CHANGELOG.md
  docs/architecture/adr-008-app-caller-cbs.md
  modules/apps/callbacks/callbacks_test.go
  modules/apps/callbacks/ibc_middleware.go
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/callbacks/replay_test.go
  modules/apps/callbacks/transfer_test.go
  modules/apps/callbacks/types/callbacks.go
  modules/apps/callbacks/types/callbacks_test.go
  modules/apps/callbacks/v2/ibc_middleware.go
  modules/apps/callbacks/v2/ibc_middleware_test.go
  modules/apps/callbacks/v2/v2_test.go
Labels: backport-to-v10.0.x, backport-callbacks-to-v0.3.x+ibc-go-v10.0.x

#8054 fix: upgrades after moving ics20-2
  Makefile
  e2e/testsuite/query/queries.go
Labels: backport-to-v10.0.x

#8060 fix: remove packet data remarshaling
  modules/apps/transfer/types/packet.go
Labels: backport-to-v10.0.x, backport-to-v8.6.x, backport-to-v7.9.x
