Repository cosmos/ibc-go, pull requests merged in 2025-05, with the labels that each got.

#8354 chore: bumped go version used by wasm dockerfile
  modules/light-clients/08-wasm/Dockerfile
Labels: backport-to-v10.2.x

#8350 chore: remove modules/core/specs
  modules/core/spec/01_concepts.md
Labels: backport-to-v10.2.x

#8371 e2e: Create only required number of chains.
  CHANGELOG.md
  e2e/README.md
  e2e/ci-e2e-config.yaml
  e2e/go.mod
  e2e/go.sum
  e2e/tests/core/02-client/client_test.go
  e2e/tests/core/03-connection/connection_test.go
  e2e/tests/interchain_accounts/base_test.go
  e2e/tests/interchain_accounts/gov_test.go
  e2e/tests/interchain_accounts/groups_test.go
  e2e/tests/interchain_accounts/localhost_test.go
  e2e/tests/interchain_accounts/params_test.go
  e2e/tests/interchain_accounts/query_test.go
  e2e/tests/transfer/authz_test.go
  e2e/tests/transfer/base_test.go
  e2e/tests/transfer/localhost_test.go
  e2e/tests/transfer/send_enabled_test.go
  e2e/tests/transfer/send_receive_test.go
  e2e/tests/upgrades/genesis_test.go
  e2e/tests/upgrades/upgrade_test.go
  e2e/testsuite/testconfig.go
  e2e/testsuite/testsuite.go
  go.mod
  go.sum
  modules/light-clients/08-wasm/go.mod
  modules/light-clients/08-wasm/go.sum
  simapp/go.mod
  simapp/go.sum
Labels: NOT READY FOR REVIEW

#8386 chore: set up v10.3.x branch mergify and ci
  .github/mergify.yml
  .github/workflows/e2e-compatibility.yaml
Labels: backport-to-v10.3.x

#8375 feat: parse IBC v2 packets from ABCI events
  CHANGELOG.md
  e2e/tests/interchain_accounts/localhost_test.go
  e2e/tests/transfer/localhost_test.go
  e2e/tests/upgrades/upgrade_test.go
  go.mod
  go.sum
  modules/apps/callbacks/ibc_middleware_test.go
  modules/apps/callbacks/ica_test.go
  modules/apps/callbacks/replay_test.go
  modules/apps/callbacks/transfer_test.go
  modules/apps/transfer/ibc_module_test.go
  modules/apps/transfer/keeper/relay_test.go
  modules/apps/transfer/transfer_test.go
  modules/apps/transfer/v2/ibc_module_test.go
  modules/core/04-channel/v2/keeper/msg_server_test.go
  simapp/go.mod
  simapp/go.sum
  testing/events.go
  testing/events_test.go
  testing/solomachine.go
Labels: backport-to-v10.3.x

#8391 chore: lint
  modules/apps/transfer/v2/ibc_module_test.go
Labels: backport-to-v10.3.x
